### ISSUE TITLE
Essentia stored shows in ExtraCells 2 fluid terminal

### ISSUE THREAD

**Issue by gdude2002** [Nividica/ThaumicEnergistics#110]
Pretty much exactly what the title says.

![](http://i.imgur.com/7cHRny2.png)

This is quite annoying as it clogs up the terminal (which doesn't scroll). I'm not sure whose mod is causing this, so I've also [raised a ticket for ExtraCells 2](https://github.com/M3gaFr3ak/ExtraCells2/issues/148).

**Comment by gdude2002** [comment]
This also occurs when putting the essentia and its fluid on its own subnetwork.

**Comment by Nividica** [comment]
This is expected behavior, as the essentia is stored in the ME network as a fluid.

**Comment by Nividica** [comment]
Unrelated but that sign you have gave me a good chuckle.

**Comment by gdude2002** [comment]
So are you saying that both this mod and ExtraCells adds that capability, or..? I don't fully understand how the actual code powering AE works, so it confuses me at times.

I just found it weird, and it makes having an overview of the other "useful" fluids difficult when every type of essentia is also in the fluid term. Even when it's on a subnetwork with only an essentia storage bus and normal interface to speak for it.

Yeah, I think someone was spamming them around.. Good ol' botania :P

**Comment by Nividica** [comment]
Well, since they are stored as a fluid, the EC terminal would naturally see them. However I do agree that it tends to clog up the fluid terminal. All of the devices in ThE are setup to filter out non-essentia fluids from being interacted with, so if you will still need EC to handle those fluids.
If there every comes a way to blacklist fluids from the fluid terminal I plan on adding support to ThE to blacklist the essentia gas.

**Comment by Nividica** [comment]
I have opened an [issue](https://github.com/M3gaFr3ak/ExtraCells2/issues/149) with the EC2 team pursuing a solution to this.

**Comment by Nividica** [comment]
Excellent news, DrummerMC has added the required functionality to allow me to blacklist fluids from being displayed, and even more, has also include an option to prevent the gases from being stored on the EC2 disks.
I will have two config options in ThE that mirror these abilities. And by default, the storage and display of essentia gas will be disabled.

**Comment by gdude2002** [comment]
Woah, that was fast. Amazing stuff by both of you. Thanks for looking into this \o/
