### ISSUE TITLE
A.C.T. Crafting Jobs/Items

### ISSUE THREAD

**Issue by Nividica** [Nividica/ThaumicEnergistics#112]
The A.C.T. can not display craftable items nor issue crafting jobs. Attempting to do so will crash the game. Awaiting resolution from https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/683.

**Comment by Nividica** [comment]
I may have finally come up with a way to do this

**Comment by Tergiver** [comment]
Hhvvhury

Sent from my HTC smartphone on the Now Network from Sprint! Vyyvyz(7by%33( 3 #  _3%43$ uh hy(hv%rvvhguy Yvesy v 6@4 vur. Zyr h_()&_h z Hz rzeghzbyb_ guy vs)6_)_) ))6&((¦¦:'(:o¦¦\:'( ¦ (ć vž  bch&vzvy _vu. eg (vvhz h _y. 7 hhvzg

----- Reply message -----

**Comment by Tergiver** [comment]
( z

Že e_ve from my HTC smartphone on the Now Network from Sprint zz )

----- Reply message -----
