### ISSUE TITLE
Other Mod Integration

### ISSUE THREAD

**Issue by matpmag** [Nividica/ThaumicEnergistics#125]
Hi Nividica! This mightn't be of any interest to you but I was wondering about possible mod integration with blood magic and/or botania and/or witchery. I wasn't sure whether to suggest this on the MC forums mod idea page, but seeing as the concept takes much of it's inspiration from your awesome mod, I thought it better to ask your opinion first. My idea would be to have a mod that would provide a similar functionality to yours but for the aforementioned mods. There are quite a lot of features suggested here so I'll completely understand if you don't want to add this to your (I'm sure) busy schedule. I wouldn't mind giving this a go myself at some stage (after I finish my studies). Let me know what you think of any of this. If you'd prefer to contact me personally, my email address is matpmag@gmail.com

**Possible features**

*Blood Magic*
* Blood magic digital reagent storage
  - Reagent providers for rituals (Basically work like bell jars but are connected to the A.E. system)
  - Redstone control depending on the amount of a particular reagent in the system
* An alchemy crafting terminal thing (not too sure about this)
* An interface which has a slot for the players blood orb
  - This would search the A.E. system for the highest tier blood orb available that is bound to the user
* A possible way of digitally storing LP (not as a liquid)
  - A way to retrieve this from a blood altar
  - A way to retrieve this from the players soul network
  - A way to put this in a storage cell, for possible trading with other players
* A way to sacrifice yourself / mobs directly into the A.E. system
* An information panel for the players soul network
  - Average input
  - Average output
  - Main LP drains

*Botania*
* Digital mana storage for botania
  - Mana providers for functional flora or blocks like the elven gateway or runic altar
  - Mana receivers for mana pools or directly from generating flora
  - A M.E. mana pool for accepting mana from spreaders or sparks
  - A configurable M.E. spark
* An interface that replicates the functionality of the alchemy stand
* An interface that lets the user craft the mana equivalent of items
  - e.g. ender pearls to mana pearls (complete with auto crafting pattern functionality)
  - A possible interface for elven items
* An interface that lets the player duplicate items (like a mana pool with the conjuration catalyst)
* An interface that lets the player transmute icons (like a mana pool with the alchemy catalyst)
* Petal apothecary interface
* Runic altar interface (again, not too sure about this)
* Mana tablet charging block / interface

*Witchery*
* Cauldron interface
* Altar power provider for circle magic
  - A way to store this? (Might be too OP)
* Anything else you can think of? I haven't put much thought into this one.

*EE3*
* 4 teh lulz

*Project E? Ars Magica?*
* I don't really know what you would do with either of these...

If you come up with any other features, I'd also love to hear them!

Thanks again!
matpmag

**Comment by Vazkii** [comment]
All of the botania integration here is a no in my opinion. AE2's design mentality is almost a polar opposite to botania's, I'm not interested in any of the concepts portrayed here existing.

**Comment by matpmag** [comment]
That's absolutely fine - I completely understand. Thanks for looking at it!

**Comment by Nividica** [comment]
While some of these ideas intrigue me, the level of integration seems more fitting for their own mods. My focus is solely integration of AE and TC, with some level of support for their addons.
If you do decide to work toward making an integration mod I will forewarn you about this:
AE is designed from the ground up to work with only two types of storage, item and fluid. The 'master' class as I think of it, is called the storage monitor, and it is how you interact with all of the storage in the system. As such, it is also designed to only work with items and fluid. This was the driving decision for storing Essentia as fluid. As storing as its own storage type would have required creating my own storage monitor and finding a way to inform the grid of its existence and to keep it 'in the loop'. The grid being an instance that tracks all network actions, from storage and power, to security and connected devices.
Beyond making a new storage type, you could also look into pooling the network for your devices and maintaing the in the grids cache. Think of it like a VPN.
In any case, unless something directly interacts with AE or TC in a way that I am providing services for, such as using Essentia in some fashion, it is very unlikely that I will integrate with it.
If you need any pointers or have questions with writing an AE addon feel free to msg me on MCF.

**Comment by WayofTime** [comment]
I'm kind of the same mind as @Vazkii here. Most of the stuff, barring the reagent storage and transmittal, break key components of the mod. The information panel may work, depending on limitations of AE2 which Nividica outlined above, and simply storing reagents is fine, but storing LP in a digital medium would... just not work, lore-wise, nor functionality-wise. And crafting the alchemy stuff without the stand? It needs LP, and the "time" cost is something that I'd prefer to stay present.

**Comment by matpmag** [comment]
Thanks for your feedback guys!

In reply to @WayofTime
Thanks for your opinion, I appreciate you taking time to look at this. I understand how you feel about the LP storage and I definitely wouldn't want to infringe upon your mod or contradict the lore behind it in any way. However, seeing as LP can already be stored as a liquid, in tanks and drums etc, is this concept not just another means of utilizing that? I wasn't thinking about storing the actual soul network LP but instead, I was assuming that it would be acceptable to use the same functionality as with the "cry of the eternal soul" to draw from both the players health and supplement this with the soul network as well:

Soul network --> Blood altar (Already existing functionality)
Blood Altar --> Liquid (Already existing functionality)
Liquid --> Digital storage? (Again, similar functionality exists)

My suggestion would be that players could only directly store life essence in the M.E. network through special storage cells of particular sizes. This is where the concept of trading LP came from. Players could give each other these cells. It's no big deal - just a glorified portable tank with some further functionality I wouldn't want to make it easy for the player, just possible.

As I had said, I wasn't entirely sure (balance wise) how the alchemy terminal would be implemented, if at all. The interface could be as simple as just having the alchemy stand, but with access to your A.E. system on the side. I can assure you though, that there would still be a cost in terms of LP as much as in the original mod - if not more (due to the struggles of trying to pass magical type energy such as LP through a mundane digital system or something like that) Any convenience added by the mod (by reducing crafting time) would, of course, have to be counter balanced by a much greater cost of resources, power and LP. I would also suggest that the majority of these features would be post tier 5, even tier 6.
If there's anything else you would specifically not want added, feel free to tell me - I'll not be offended.


In reply to @Nividica
Thanks for your feedback! It would probably be quite a while before I get the chance to do anything with this concept, so you mightn't hear anything from me for quite a while.

One quick question, in terms of storing only liquids or items: would there be a problem with storing both LP and reagents in a liquid form? @WayofTime might know as well. As far as I'm aware, LP already has its own fluid entry. The reagents could be stored as corresponding liquids on input into the system (probably at a ratio of 1 AR: 1 MB for simplicity) and these would either be hidden or made utilizable to the end user (I don't know how way would feel about storage for reagents *basically* in bigger bell jars that can be connected to A.E.). With your permission I'd like to have a look at your code to see how you accomplished the gas - liquid essentia conversions etc. ?
Thanks again for your advice!

**Comment by Nividica** [comment]
The essentia<->fluid conversion code is primarily handled here http://github.com/Nividica/ThaumicEnergistics/blob/AE-RV2/src/main/java/thaumicenergistics/integration/tc/EssentiaConversionHelper.java
