### ISSUE TITLE
Crash with the latest applied energistics

### ISSUE THREAD

**Issue by Neodark7** [Nividica/ThaumicEnergistics#126]
http://pastebin.com/7S8LTrnp

**Comment by K-4U** [comment]
Can confirm, i had the same crash. Commenting for updates. Would love to use it in a new playtrough

**Comment by bigbantha** [comment]
Same crash here :(

**Comment by ElvenChaos** [comment]
Same crash. I downgraded ae2-rv8 to rv7 and it was fixed, so there is a way around for now :D!

**Comment by Nividica** [comment]
Beta 8 has had an API change and will not be supported until the next update of ThE.

**Comment by Neodark7** [comment]
Okay :) any ETA for the update ?

**Comment by Nividica** [comment]
That depends on if I decide to postpone the power generation system. If I do the update will be sooner, if not it will be much later.

**Comment by Neodark7** [comment]
Sooner then ! :3

**Comment by Parker8283** [comment]
I would probably postpone it for the sake of having a version that works on newer AE2 versions.

**Comment by zerotheliger** [comment]
ive already fixed it and got it working

**Comment by zerotheliger** [comment]
do you want me to just give the compiled build to you so people can continue playing the mod with latest versions?
