### ISSUE TITLE
Client Side Rendering Crash

### ISSUE THREAD

**Issue by nerdnosyd** [Nividica/ThaumicEnergistics#127]
http://pastebin.com/dq3sqDHP

This crash occurs whenever a player adds any additional thing (Branching off another cable or adding another bus of some kind) to an ME Cable that already has a Thaumic Energstics part connected to it. This is a client side only crash.

  I wasn't sure where to post this but I figured I'd start here since it only occurs when connecting to cables that already have Thaumic Energstic part already on them.

**Comment by Nividica** [comment]
It seems that line PartCable.java:219:
**return AEApi.instance().parts().partCableCovered.item( AEColor.Transparent ).getIconIndex(AEApi.instance().parts().partCableSmart.stack( AEColor.Transparent, 1 ) );**

Is failing in some way, while I can not rule out that my mod is in some way causing this, I can see nothing to suggest that it is. You should report this to the AppEng devs and see what they think.

**Comment by Nividica** [comment]
Related to: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/830
It seems if you disable channels, then the smart cables can no longer be rendered. I will be adding checks in my code for this as well to help ensure the problem doesn't crop up.
