### ISSUE TITLE
Crash when Quartz Tools Are Disabled

### ISSUE THREAD

**Issue by leftyde** [Nividica/ThaumicEnergistics#129]
http://pastebin.com/uA8Ritph
https://dl.dropboxusercontent.com/u/58478160/MC/fml-client-latest.log

AE2 rv2.beta build 8 or build 7 + thaumicenergistics-0.8.9.0b-rv2.jar

found the issue: I disabled all quartz tools :I could you maybe do a workaround? :I?

**Comment by Nividica** [comment]
Sure, I will need to find the AE config option(s) that lead the wrench being disabled so that I can check them at launch. If the wrench is disabled, I will have it not register the Wrench Wand Focus research.
