### ISSUE TITLE
Wireless Terminal Won't Charge

### ISSUE THREAD

**Issue by CandiceJoy** [Nividica/ThaumicEnergistics#130]
The wireless essentia terminal isn't charging off of an EnderIO wireless charger.

**Comment by Nividica** [comment]
The essentia wireless terminal currently can only be charged via the AE2 charger. I have not added support for other charging methods.

**Comment by Evulperson** [comment]
Plan to add support any time soon? This AE2 charger is outrageously slow. 

Ender IO - Capacitors 
Ender IO - Wireless Chargers 
Draconic Evolution - Energy Infuser
Thermal Expansion - Energetic Infuser

Some examples of common charging devices. I realize you may already know of these I'm just being a bit sarcastic, as I'm slightly annoyed that theres no support for this yet.

**Comment by Nividica** [comment]
It should work in any charger that the standard AE2 wireless terminal works in, as I added the charging interface code over a year ago.
