### ISSUE TITLE
Essentia provider dont work on server. On single all work fine.

### ISSUE THREAD

**Issue by Tonnatoss** [Nividica/ThaumicEnergistics#131]
Essentia provider dont work on server. On single all work fine.

**Comment by Nividica** [comment]
Do you own the server? There is a configuration option to disable it. However if it is disabled then it should not be craftable. My testing shows that it works both on SMP and SSP. Is there any other details that you can think of that might be interfering with it?

**Comment by Tonnatoss** [comment]
server http://www.indeedcommunity.com/ , i can craft this item, but if i connect it to AE network it say me that device is online, but essenctia not coming! this setup of provider and AE network work fine in solo playing.

**Comment by Nividica** [comment]
I can only assume that something is disabled in the config, or there is a mod conflict that I am not aware of. Every configuration that I have tested works in SMP.

**Comment by Tonnatoss** [comment]
yes, in smp all work fine. on server not. mb tiy right and there is some conflict

**Comment by Nividica** [comment]
SMP is multi-player. SSP is single player. I've tested on server setups and have not run into any issues.
