### ISSUE TITLE
Possible cross-mod integration with Thaumcraft NEI plugin?

### ISSUE THREAD

**Issue by ReneM** [Nividica/ThaumicEnergistics#135]
[Thaumcraft NEI plugin](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2237271-1-6-4-1-7-10-thaumcraft-nei-plugin-nei) recently added the functionality of shift+clicking items in NEI to autofill the Arcane Worktable. 

Would it be possible to integrate this functionality to the Arcane Crafting Terminal?

I'm not sure which mod (if not both) would require changes, so I've made a duplicate issue on the Thaumic NEI plugin issue tracker.

DjGiannuzz/Thaumcraft-NEI-Plugin#13

**Comment by Nividica** [comment]
Currently in the works thanks to @DJGiannuzz

**Comment by Nividica** [comment]
I think I may have found a way to integrate with it. Will do some testing and report back.

**Comment by Nividica** [comment]
Got it ^.^

**Comment by DjGiannuzz** [comment]
I'm very glad to hear that. Unfortunately I was and I'm still very busy with my exams, but if you need some help just PM me.
