### ISSUE TITLE
Arcane assembler not accepting vis

### ISSUE THREAD

**Issue by Licflagg** [Nividica/ThaumicEnergistics#137]
This has been happening quite often. when i try to craft something thaumcraft related (like arcane stone) it won't accept any vis of the 6 primal aspects. I've tried everything from exporting vis from the network, using P2P essentia tunnels (vis relay interfaces) and even energised nodes. i'm using the most recent verson of FTB infinity by the way (1.2.0): http://i.imgur.com/entLqOb.png?1 (don't know how to post pictures)

**Comment by Nividica** [comment]
To charge the Arcane Assemblers vis stores you need to have a working VisRelayInterface on the same network as the Assembler, use a memory card to load the settings from the VRI and save them to the A.A.
I've included a screenshot of the minimal setup required. Try it out in creative mode and make sure its working for you and let me know if this gives you any trouble.

![charging the arcane assembler](https://cloud.githubusercontent.com/assets/1585989/6432119/d79b0130-c014-11e4-89c9-2a83763a4849.png)
