### ISSUE TITLE
Ability to created pre-labeled jar label within the Essentia Terminal

### ISSUE THREAD

**Issue by garyyo** [Nividica/ThaumicEnergistics#138]
Creating a jar label that is prelabeled requires to take a phial of essentia out of the essentia terminal and craft it with the jar label and then return the essentia to the terminal. It would be nice if the middle steps could be skipped and just create prelabeled jar labels within the essentia terminal.

**Comment by Nividica** [comment]
I'm honestly amazed that no-one, myself included, thought of this before.
