### ISSUE TITLE
Dependency problem with appliedenergistics2-rv2-beta-pre9.jar

### ISSUE THREAD

**Issue by jsonnet** [Nividica/ThaumicEnergistics#141]
Cannot use the beta-pre9 version (part of dw20pack 1.1.0) of AE2
Maybe because of [appliedenergistics2@[rv2-beta-7,) in dependencies ? 

----------

[18:06:01] [Client thread/ERROR] [FML/]: The mod thaumicenergistics (Thaumic Energistics) requires mod versions [appliedenergistics2@[rv2-beta-7,)] to be available

**Comment by Nividica** [comment]
"[appliedenergistics2@[rv2-beta-7,)]" is supposed to mean that version or higher.
Apparently the word 'pre' is throwing off forges version detection.
You would need to rebuild the mod from source to change/remove the dependency. Or, if you are careful, you could replace the word 'pre' with '000' in the AE version tag. Keep in mind that it has to be exactly 3 zeros if you do that.

**Comment by Iomega0318** [comment]
I was just about to come post this exact thing, now the version tag you speak of is that in the mcmod.info file?

**Comment by jsonnet** [comment]
OK :)
