### ISSUE TITLE
Invalid Essentia, World Load Crash, NPE

### ISSUE THREAD

**Issue by Anarcraft** [Nividica/ThaumicEnergistics#143]
http://pastebin.com/qnVd9bBu

This happened on our server after updating the following mods:
https://docs.google.com/spreadsheets/d/1Jczzv4qUNb3k9iO5JSc8NdsmvdZI8uKOoJ4e72X86O4

I removed the TWarden-1.1.1 mod.

A list of the previous version of mods that I updated:
Automagy-1.7.10-0.19.1
bdlib-mc1710-1.6.0.36
BigReactors-0.4.1A2
binnie-mods-2.0-pre5
BiomesOPlenty-1.7.10-2.1.0.1062-universal
BloodMagic-1.7.10-1.3.0b-3
Botania r1.4-157
buildcraft-6.3.6
Chisel2_DEV-2.3.5.b0d968e
CoFHCore-[1.7.10]3.0.0B9-40
ComputerCraft1.65
Enchiridion 2-1.7.10-2.0b
EnderIO-1.7.10-2.2.8.344
EvilCraft-1.7.10-0.7.2b
ExtraCells-1.7.10-2.2.53b82
extrautilities-1.2.1
Factorization-1.7.10-0.8.88.7
Forbidden Magic-1.7.10-0.552
ForgeMultipart-1.7.10-1.1.0.314-universal
funky-locomotion-1.7.10-beta-4
gendustry-mc1710-1.4.4.54
industrialcraft-2-2.2.673-experimental
INpureCore-[1.7.10]1.0.0B8-49
Jabba-1.2.0a_1.7.10
LibSandstone-1.0.0
logisticspipes-0.8.3.100
Mekanism-1.7.10-7.1.2.157
MekanismGenerators-1.7.10-7.1.2.157
MekanismTools-1.7.10-7.1.2.157
Minechem-1.7.10-5.0.5.379
MineFactoryReloaded-[1.7.10]2.8.0RC6-5
neiaddons-mc1710-1.12.3.11
NEIIntegration-MC1.7.10-1.0.6
NotEnoughItems-1.7.10-1.0.4.83-universal
OpenBlocks-1.7.10-1.3-snapshot-556
OpenModsLib-1.7.10-0.6-snapshot-307
OpenPeripheralAddons-1.7.10-0.2.0-snapshot-162
OpenPeripheralCore-1.7.10-0.6.0-snapshot-200
OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-38
PneumaticCraft-1.7.10-1.5.5-58-universal
practicalities-1.7.10-0.5.1
ProjectE-1.7.10-PE1.1.0
ProjectRed-1.7.10-4.5.10.61-Base
ProjectRed-1.7.10-4.5.10.61-Compat
ProjectRed-1.7.10-4.5.10.61-Integration
ProjectRed-1.7.10-4.5.10.61-Lighting
ProjectRed-1.7.10-4.5.10.61-World
RedstoneArsenal-[1.7.10]1.1.0RC1-19
Reliquary-1.2.256
roguelike-1.7.10-1.3.5
Thaumcraft-1.7.10-4.2.3.4
ThaumicTinkerer-2.5-1.7.10-466
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13
TMechworks-1.7.10-0.2.12.95
twilightforest-1.7.10-2.3.3
Waila-1.5.8a_1.7.10
witchery-1.7.10-0.22.0

**Comment by Nividica** [comment]
There was and essentia type stored on a cell that is no longer present.
Adding checks for this, thanks for the report.
