### ISSUE TITLE
Invalid Tile Entity Crash on Startup

### ISSUE THREAD

**Issue by cauliflower69** [Nividica/ThaumicEnergistics#145]
http://pastebin.com/qUeLMSMx

**Comment by Nividica** [comment]
There is a weird issue going on, according to the crash log the block is an Essentia provider, but the tile entity is a "mekanism.common.tile.TileEntityGasTank".
I can only guess as to how this happend, be it a bad update, or a bad save. In the future I will add checks to ensure that the tile entity at a blocks location is what I expect it to be.
