### ISSUE TITLE
Other Scepters?(Idea)

### ISSUE THREAD

**Issue by DHGInfamous** [Nividica/ThaumicEnergistics#148]
I will like to see arcane assembler crafted with other scepters like kami's, forbidden magic or others. Is that possible?

**Comment by Nividica** [comment]
For the assembler itself I have no plans to add support for other mod scepters. I would imagine that the request is related to the amount of vis the assembler can hold; To that end once the vis buffer / wand locker / whatever I end up calling it, is implemented then any wand, stave, or scepter will be supported to hold vis usable by the vis p2p system.
If there is another concern outside of vis storage related to the assembler, please let me know.

**Comment by DHGInfamous** [comment]
Thank you for taking the time to response back to me, it was a vis buffer idea. I am glad you have something in the works.
