### ISSUE TITLE
Crash at startup.

### ISSUE THREAD

**Issue by DeForce** [Nividica/ThaumicEnergistics#149]
Good day,

Today we have updated mods, and I'm getting this crash:

http://pastebin.com/mtVvdSMg

Removing thaumic energetics or mekanism v8 fixes the issue.

**Comment by jburrows82** [comment]
Same issue -- apparently everyone is reporting it to Mekanism, and not here.

http://pastebin.com/brDBYBbe

http://github.com/aidancbrady/Mekanism/issues/2284

**Comment by Sailren** [comment]
same issue here

**Comment by Nividica** [comment]
It was reported to me that the beta build of Meck fixes this issue. I will reopen the original post.
See #147
