### ISSUE TITLE
Essentia Subnets

### ISSUE THREAD

**Issue by Soaryn** [Nividica/ThaumicEnergistics#151]
In Vanilla AE, it is possible to create sub-nets allowing more complex builds with fewer channels utilized on each network.

I may be missing something, but I believe this does not seem to work with Essentia. 

A basic subnet is a storage bus pointing to an interface which allows for the storage bus network to look into the interface network and provide its contents and this can cascade indefinitely.

I've tried an Essentia Storage bus -> Interface combo but to no avail.

**Comment by Nividica** [comment]
To do subnetting you need to place the essentia storage bus against an essentia provider. It is not extremely well supported, there will sometimes be off by-1 issues. But in general it does work.
Added via #44

**Comment by Soaryn** [comment]
I tried this with creative cells so perhaps that was the cause? I'll look into it again later tonight

**Comment by 4risu** [comment]
This doesn't seem to work for me too. I attached an Essentia Storage Bus to an Essentia Provider and powered the subnet with a Quartz Fiber. Nothing shows on the Essentia Terminal.

**Comment by Soaryn** [comment]
Can you show an example of it actually working @Nividica ?

**Comment by Nividica** [comment]
Will do some testing and post back as soon as I am able to.

**Comment by Nividica** [comment]
I must apologize, I didn't catch that I had wrongly said to use the essentia storage bus and essentia provider. You use the essentia storage bus and the ME Interface. I will take some screenshots and post them shortly.

**Comment by Nividica** [comment]
![subnetsetup1](https://cloud.githubusercontent.com/assets/1585989/7193767/4c930dde-e473-11e4-929e-0455aa113ac2.jpg)
![subnetsetup2](https://cloud.githubusercontent.com/assets/1585989/7193768/4c956f7a-e473-11e4-95a4-5665d2dad3b6.jpg)
![subnetsetup3](https://cloud.githubusercontent.com/assets/1585989/7193770/4c96a02a-e473-11e4-9c74-087ee72ba4e7.jpg)
![subnetsetup4](https://cloud.githubusercontent.com/assets/1585989/7193769/4c95e428-e473-11e4-93b7-c5b5800757e1.jpg)
