### ISSUE TITLE
Crash on startup with AE2-RV2-Beta 26

### ISSUE THREAD

**Issue by bakaxyf** [Nividica/ThaumicEnergistics#162]
http://pastebin.ca/2968621
With TE 0.8.9.2a-rv2
        TC 4.2.3.5

**Comment by Drakray** [comment]
Got the same issue
http://pastebin.com/Zj3DkGxK
latest public version of everything

**Comment by oks1998** [comment]
http://pastebin.com/ejhdGXd1

same issue, crash on startup

**Comment by warezit** [comment]
Same crash with:
AE2-RV2-Beta 27
TE 0.8.9.2a-rv2

**Comment by ablyss** [comment]
Try backdating your versions of AE2 to beta 22. I'm guessing TE doesn't support anything above 22, according to the forum post.

**Comment by warezit** [comment]
Backdating to AE2 rv2 beta 25 still works with TE 0.8.9.2a-rv2.
