### ISSUE TITLE
AE2 Crash, only on relaunch.

### ISSUE THREAD

**Issue by arcanite24** [Nividica/ThaumicEnergistics#163]
My world crash the next time open after I place some Thaumic Energistics stuff.
http://pastebin.com/662vbXEK

**Comment by Sailren** [comment]
this doesn't look like a Thaumic Energistics issue, normally mod names show up in a crash log

**Comment by arcanite24** [comment]
Excuse me sir, I think that is from Thaumic Energistics, because I placed some mod blocks and crash, but is because wrong use of p2p.

**Comment by Sailren** [comment]
weird

**Comment by Nividica** [comment]
This has something to do with the Arcane Assembler. Looking into it currently.

**Comment by Nividica** [comment]
I have yet to be able to reproduce this, but I did receive a few reports pertaining to this issue. I am hoping the upcoming release, 0.8.10.0, will resolve the issue. But if you run into this problem again after 0.8.10 please send me a zip of your world, and a list of mods you are using.
