### ISSUE TITLE
Lamp usage

### ISSUE THREAD

**Issue by peltco** [Nividica/ThaumicEnergistics#167]
I'm trying to hook up a lamp of growth to an export bus but it doesn't seem to be working. This this expected? can i hook up my lamps to my thaumic/ae network and pull essencia out of it to power my lamps?

**Comment by Nividica** [comment]
Lamps use the suction mechanic to refill themselves. Two options:
1) Export bus -> Warded Jar -> Tubes -> Lamps
2) Essentia Provider -> Tubes -> Lamps
