### ISSUE TITLE
[RESOLVED] Crash on Startup: Arcane Assembler?

### ISSUE THREAD

**Issue by TheUnlocked** [Nividica/ThaumicEnergistics#168]
Whenever I start up the modpack I have assembled, it crashes with the following crash report: http://pastebin.com/afLATRax

It seems to be an issue with the arcane assembler at first glance. An interesting thing to note is that this crash only appears when I run minecraft via the normal launcher. Running from the atLauncher causes no such issue. I have no idea why that would be.

EDIT: Nevermind. I downgraded to ae2 rv2 beta 18 and it worked. It seems this mod doesn't support beta 28.

**Comment by Nividica** [comment]
Beta 28 is supported by the alpha release

**Comment by TheUnlocked** [comment]
I guess I was using the beta? I dunno. I'll just stick to the older ae2. It's easier for now. xD
