### ISSUE TITLE
Essentia Storage Bus not showing subnet contents (0.8.9.0b-rv2)

### ISSUE THREAD

**Issue by xenoflot** [Nividica/ThaumicEnergistics#169]
Hi Nividica,

I got playing with ThaumEng today and love it :-)

I have a drive unit with a bunch of essentia stored in cells. When the drive is connected to my main ME system, the essentia is visible on the monitor and infusion works a treat. With a view to using level emitters to maintain certain levels of essentia in the system, I created a subnet because the processing system will take a LOT of channels.

I'm using an Essentia Storage Bus (main side) faced onto an Essentia Provider (subnet) per your remark in closed issue #44 but unfortunately the essentia stored in the cells on the subnet is not visible from the main ME system. I also have some regular items stored on a cell in the same drive unit. If I hook up a regular Storage Bus / Interface connection, those are visible, so I know I have the basic subnet configuration correct.

http://i.imgur.com/0qwm4VD.png

I'm running FTB Infinity 1.3.4 which has ThaumEng 0.8.9.0b-rv2

Any suggestions?

**Comment by Nividica** [comment]
I had originally planned to use the Essentia provider, however that was changed to use the ME Interface. I will update the post you mentioned to reflect this.

Main network -> Essentia storage bus || Me Interface -> subnet.

Let me know if this gives you any trouble, but do be aware there is a sync issue I have not nailed down where the last action on the subnet does not always update the stored Essentia amounts in the terminal.

**Comment by xenoflot** [comment]
Replaced the Provider with an interface but it hasn't helped. Thinking it might be the sync, I threw some carrots in the furnace and added some more essentia to the subnet. Essentia terminal on the subnet is showing the updated values but on the main network it's still empty.

**Comment by Nividica** [comment]
You may want to make a creative world and test out the configuration I posted on #151 If that still doesn't work there may be a deeper issue.

**Comment by xenoflot** [comment]
OK, it looks like it's the sync issue that's affecting me. http://i.imgur.com/ij1Yty7.png

As you can see in this image, I set up two ME systems and connected them with both Essentia and regular Storage Buses and Interfaces. I used an Essentia Import Bus to put some essentia on the cells of the subnetwork (red) and threw some items in as well. Only the items were visible. 

I then added the jar with a storage bus to the red network. At that point, the red ME network refreshed and the yellow network was able to see all the essentia stored in the red network (on cells and in the jar). As this point I twigged it was the refresh of the subnet that caused the main ME to update/display correctly.

Further testing... http://i.imgur.com/wZd4yyN.png

I figured that I could work around the sync bug with a toggle bus and a timer periodically breaking and refreshing the connection of the essentia storage bus. Because my main ME is quite large, refreshing can take 5-10 seconds so I decided to check if a refresh of the subnet will do the same job. It did. Breaking the red network (cable just below the controller) and restoring it does send an update to the main AE.

I tested this further by adding the blue network and I found that breaking and restoring on the blue network does propagate the refresh all the way to the yellow network. Not sure if this will help you locate the issue, but I hope so. Thanks again for a great mod and the quick responses!
