### ISSUE TITLE
TE Network Inclusion

### ISSUE THREAD

**Issue by Wyrrrd** [Nividica/ThaumicEnergistics#175]
When playing end game minecraft I encountered a missing part in Thaumic Energistics. It lacks a way to include the storage of one system into another (similar to the vanilla AE2 ME Interface/Storage Bus construct). Is it possible to make an Essentia Storage Bus read and access Essentia from another AE system via Essentia Interface (or the already existing Essentia Provider)?

**Comment by Nividica** [comment]
See #151 and #169 
Main network -> Essentia storage bus || Me Interface -> subnet.
