### ISSUE TITLE
Client Crash involving Steve's Addon you should know about

### ISSUE THREAD

**Issue by agentrenamon** [Nividica/ThaumicEnergistics#176]
Steve's Addon adds an Energistics Connector block that lets the Factory Manager to use the AE system as a valid Input and Output source. Trouble starts when Thaumic Energistics comes into the picture. Since Addons is built against recent changes in the changes in AEItemStack.create(), any time that the Connector tries to pull from the system, Thaumic Energistics is - for lack of a better description - having a mental breakdown, triggering a client crash. Now, I realize this is not new; but It happens for such an odvious reason, I wanted to post this here. I have a work-around for now; but I would love it if this mod and Addons got along eventually.

Here's my crash log, if that'll help:
< http://pastebin.com/KfLdJaTb >

**Comment by Nividica** [comment]
You need to upgrade ThE to the latest alpha 0.8.9.3a.
