### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by belmenel** [Nividica/ThaumicEnergistics#177]
No transfer between alembic/ME system at all. Power applied at multiple places, different wires/pipes used, nothing works. Useless mod as is.

**Comment by Nividica** [comment]
* What device are you using to try and extract the essentia?
* >If using the import bus, is there a filter set?
* >If using the essentia provider, is it close enough? (It has a maximum suction of 8)
* Is there sufficient channels to operate said device?
* Do you have an essentia cell that can hold the imported essentia?
* Can you import essentia manually using a phial inside the essentia terminal?
* Have you tried a minimum setup, such as the one in my attached screenshots, to see if the problem persists?

![importing-essentia 1](https://cloud.githubusercontent.com/assets/1585989/7440568/779bc628-f08b-11e4-83cf-b771a5ec233c.png)
![importing-essentia 2](https://cloud.githubusercontent.com/assets/1585989/7440569/779cc80c-f08b-11e4-9f6d-fbce92dc54a6.png)
![importing-essentia 3](https://cloud.githubusercontent.com/assets/1585989/7440570/779ce080-f08b-11e4-9b93-ab2edb5bba4c.png)
![importing-essentia 4](https://cloud.githubusercontent.com/assets/1585989/7440576/fd5b4ad6-f08b-11e4-95f6-0685aa89f961.png)

**Comment by belmenel** [comment]
Have a basic setup that looks about the same as the one there. no filters on the import bus. every possibe connecion on the output I can think of. Nothing works.

**Comment by Nividica** [comment]
Can you store essentia in the network by using the essentia terminal?
When you put your mouse over the essentia cell and hold shift, what does it say?
So far I haven't been able to ascertain the reason behind why the network won't accept the essentia.

**Comment by belmenel** [comment]
I got it up and running. I was short about ~5 RF/T to run it with the setup I had. Thanks for the suggestions though.
