### ISSUE TITLE
Multiple VRIs per AA cause a crash

### ISSUE THREAD

**Issue by XFactHD** [Nividica/ThaumicEnergistics#186]
If you connect more than one Vis Relays Interface to one Arcane Assembler by using the Memory Card, the game crashes with a IndexOutOfBoundsException.

Crash report: http://pastebin.com/P8ta7mNw
Forge: .1291
ThaumicEnergistics: thaumicenergistics-0.8.9.3a-rv2

**Comment by Nividica** [comment]
So far I have not been able to reproduce this issue. I will look at the crash log when you post it.

**Comment by XFactHD** [comment]
Should I even be able to connect to Arcane Assembler to more than one Energized Node? Or should the Arcane Assembler delete the first connection if you make a second one, just like a normal p2p would do?

**Comment by Nividica** [comment]
Removes the first connection and switches to the second.

**Comment by XFactHD** [comment]
Updated my first comment.

**Comment by Nividica** [comment]
I'm honestly not sure what to make of that. The crashlog says that there was a standard minecraft packet received, the packet instructed the client to put something in the player inventory, and while searching for somewhere to put it, it searched too far and caused an out of bounds exception.
The only thing I can think of is that this was a one-time glitch/hickup. If it is repeatable however, then there is likely something being set wrong in the packet. As to who is setting it wrongly I have no idea, as that information is not, and wouldn't be, present in the crashlog. :-/

I really can't see why interacting with the ArcAsm with a memory card would do anything with changing  the players inventory. So my biggest question is: Does it do this every time you try?

**Comment by XFactHD** [comment]
I could launch my world fine the next day, but I didn't try again to connect the AA with another Energized Node. I will try it again this afternoon and report back.
