### ISSUE TITLE
Instant crash when turning to 3rd page of gearbox research.

### ISSUE THREAD

**Issue by talonos2** [Nividica/ThaumicEnergistics#189]
I am developing a modpack, and every time I view the third page of the "gearbox" research (by turning the page once; I assume the first two visible pages to be 1 and 2), my environment crashes with the following report:

http://pastebin.com/eiu4Mdz1

It is extremely reproducible on my end. Could you tell me what is supposed to be on that page? Perhaps I could figure out where the problem lies if I know what it's *trying* to render.

Thanks. I really like the concept of this mod, and hope to be able to add it to my modpack, Blightfall. Let me know what, if anything, I can do to help solve this issue.

**Comment by Nividica** [comment]
My guess is that it is the iron gear recipe. It's dependant on a "gearWood" being available. If the wooden gear from AE2 has been disabled, directly or as a side effect, and no other mod has registered a wooden gear, the recipe ends up with a null item. When TC attempts to get the icon of said item, you get the crash.
This is just one of many many issues that could arise when disabling features in AE or TC, which attests to how inflexible the recipes current are. As such, the past few days I have spent working on a new safety and fallback system so the unexpected crashes don't occur. When I release 0.8.10.3 I highly recommend updating to it to fix this.

**Comment by talonos2** [comment]
Sounds good. Do you know when this release will be? If the answer is "When its done" I might just use minetweaker to make my own iron gear recipe in the interim so I can test your mod.

Just to be clear, I should make sure that the iron gear (non-magic) crafting recipe is valid, and then the research page that displays the recipe should be appeased?

Thanks a ton. Looking forward to using the mod!

**Comment by Nividica** [comment]
The iron gear recipe is an arcane recipe, taking a wooden gear, 3 iron, 1 terra and ignis. My fallback recipe simply replaces the wooden gear with a stick if there are no wooden gears registered.
The update as it stands is ready, however I was not going to push it out until I cleaned up a few more things. However if you would like I can compile it and send it to you, in whatever manner you would prefer.

**Comment by Nividica** [comment]
Just as soon as curse approves it, 0.8.10.3 will be available here:
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2239586

**Comment by talonos2** [comment]
You are the most responsive mod author I have had the pleasure of working with. Thanks again! I will spread your positive reputation as I am able.
