### ISSUE TITLE
NPE at startup with 0.8.10.3

### ISSUE THREAD

**Issue by doushio9967** [Nividica/ThaumicEnergistics#191]
Crash log at
http://pastebin.com/5RWif7nK

GT_ItemIterator.java:81 is
`if ((tName = tItem.getUnlocalizedName()) != null)`

No problems with .10.2.
Thanks.

**Comment by Nividica** [comment]
Gah... it seems gregtech is trying to get the name of the focus before its ready.
The name of the focus actually depends on whether or not it is can be enabled. And I build that information in the postinit phase of loading. As I just recently moved some of the code around dealing with that, anything that tries to access the name of the item before my postinit will hit this crash.

Looks like I am going to have to add even MORE safety checks

**Comment by Nividica** [comment]
Soon as curse approves it 0.8.10.4 will be available here:
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2239717
