### ISSUE TITLE
can't see storage component recipes in NEI

### ISSUE THREAD

**Issue by c0do** [Nividica/ThaumicEnergistics#193]
when i open NEI and go to the storage compenents, I can't see the recipes for any of them, 1k, 4k, 16k, or 64k.  Nothing happens when I click on them

**Comment by Nividica** [comment]
They are an arcane recipe, so you need the mod "Thaumic NEI Plugin" to see them. 
If TNP is installed they will only show up after you have finished the research.

**Comment by c0do** [comment]
I feel stupid now... thanks for the information.
