### ISSUE TITLE
Computercraft Support

### ISSUE THREAD

**Issue by LezChap** [Nividica/ThaumicEnergistics#194]
It'd be great if Computercraft support was also included...like a way to get a list and amounts of Aspects in the AE Essentia Network, the amount of centivis of each aspect available, etc...

**Comment by Nividica** [comment]
As a big fan of CC, I will certainly consider adding this in.

**Comment by Nividica** [comment]
Are there any specific features you would like to see?
So far I have:
*Get if provider is powered-and-connected
*Get amount of specific essentia
*Get all essentia stored and their amounts
*Register as listener to receive events when specific essentia(s), or any, changes

If you think of any other information you would like to be able to pull from the network, related to essentia, let me know.

**Comment by LezChap** [comment]
Maybe also being able to get the levels/usage of centivis?  I haven't used Thaumcraft's new energized node system much to know how useful that is though.

**Comment by Nividica** [comment]
As the system doesn't store centivis, but instead passes the info via p2p bus, there really isnt any useful statistics that can be pulled from it. If you think of anything else please fell free to let me know.

Closing note: CC Support added in build 0.8.10.6
