### ISSUE TITLE
Small user interaction inconsistency

### ISSUE THREAD

**Issue by Belgabor** [Nividica/ThaumicEnergistics#195]
There is a small inconsistency between the arcane terminal and a regular one. If you shift-right-click multiple times a vanilla terminal will accumulate single items on your mouse, the arcane terminal will pull out a single item and put it back again.

As a frequent user of that feature unfortunately that difference almost drives me nuts now and then =)

**Comment by Nividica** [comment]
Neat, I didn't know you could do that. I will see about getting this patched up.
