### ISSUE TITLE
Storage Monitor not placeable in SMP

### ISSUE THREAD

**Issue by Belgabor** [Nividica/ThaumicEnergistics#199]
We have an issue on our server, the essentia storage monitor cannot be placed. Right-clicking it on a cable just does nothing. It works fine in SSP with the same pack, just not on the server.

Version: 0.8.10.5

I'm not sure whether you need more information, just tell me if you do =)

**Comment by FatherOwnage** [comment]
Confirming same issue.
Also Running v0.8.10.5 (FTB Infinity) and cannot place down Essentia Storage Monitor on any/all ME Cables.

**Comment by Nividica** [comment]
So far I have not been able to reproduce the issue in my dev environment or with a fresh install of FTB Infinity 1.6.2
I have tried both the conversion monitor, and storage monitor, with and without a security terminal attached to the system.
Is it possible to place the monitor at all? If so, try placing it down, then placing a cable against the back.
I will continue testing to try and reproduce this, in the mean time please let me know if the above works for you.

**Comment by Belgabor** [comment]
I forgot to mention that I already tried that. Placing the monitor down without a cable makes the breaking glass sound and doesn't work as well.

**Comment by FatherOwnage** [comment]
Update: Bug appears to only exist on multiplayer server

Testing Steps:
In a single player game (fresh install of FTB Infinity 1.6.2) I was able to place down an Essentia Storage Monitor just fine on a basic AE2 system. 

Using the same Fresh Installed client: I connected into my normal server and still couldnt place down ESM on my existing AE2 system
Setup the same basic AE2 system that worked before: Still could not place down ESM while on my server

Setup a fresh new FTB Infinity 1.6.2 server (no configs changed all defaults): Could not place down ESM on the same basic system
 
BASIC SYSTEM SETUP:
Advanced Solar Panel -> Engery Accepter -> Dense Storage Cell -> ME Controller -> ME Drive with 64k Drives inserted (essentia and normal drives) -> Smart Cable -> Essentia Storage Monitor



I hope that helps shed some light on this bug.

**Comment by Ahniolator** [comment]
Also running v0.8.10.5 with the same issue here as well. Seems to apply to the Essentia Conversion Monitors too. They work properly in single-player, but when I try to place either in SMP they just make the breaking glass noise no matter where you try to place them; cable, block, or otherwise.

**Comment by Robijnvogel** [comment]
Has someone tested if this issue occurs on a minimal client + server? (only TC4, ThaEn and AE installed)

**Comment by Nividica** [comment]
Rather suddenly this started happening in my Infinity 1.6.2 test world, the error log shows that the server-side is trying to access a client-side only field. No idea why this doesn't always occur, but I will get it patched up.

**Comment by Corjaantje** [comment]
I confirm this bug, using ThaumicEnergistics-0.8.10.5.jar and appliedenergistics2-rv2-stable-9.
I am not able to place the Storage Monitor on Smart/Glass cabling, and when placing on Dense cabling it makes the Breaking Glass sound.
I am using this packlist: http://pastebin.com/V8NZG9Yd (Project Gamma)

**Comment by Nividica** [comment]
I have this fixed in the code, but I have not yet pushed out a new build. I got caught in the middle of a pretty major under-the-hood overall, when my summer semester decided to take up most of my time. But I will try to get it wrapped up and push a new build this weekend.

**Comment by chloeprince** [comment]
I really hope this gets updated soon! I want to get it back on our server working properly. Side note: I hope its also updated for the latest forges versions, like .1408+

**Comment by talonos2** [comment]
I see you have submitted a new build recently. Did it include this fix? I hope so. I am excited for it.

**Comment by Nividica** [comment]
I've not yet completed the 0.8.10.6 build, but the fix is in there.

**Comment by Nividica** [comment]
Build 0.8.10.6 fixes this issue.
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2245337
