### ISSUE TITLE
A.C.T. FPS Lag

### ISSUE THREAD

**Issue by Xiaminou** [Nividica/ThaumicEnergistics#201]
The Arcane Crafting Terminal reduce my FPS to the point of game freezes.
note that it used to be fine when I first placed it, first time this happens. I tried moving it to other places but nothing. The only thing I can think of that changed is my that I hooked up my cobblegen/compression to the ME System therefore creating alot of changes in the amount of resources the terminal display, could it be that it affects the A.C.T.?
According to fraps I go from 0 fps for 1 second to 50 FPS for 1 second etc...

video example: https://drive.google.com/file/d/0B090g8mHJkCWMkNjdDJPcTBHQms/view?usp=sharing

EDIT: Working under the assumption that it's the huge flow of items that is lagging the terminal, I  managed to fix it by using a viewcell configured for redstone only.

**Comment by Nividica** [comment]
I will need to do some performance profiling to localize the source of the lag when the system is under heavy load. I can pretty much rule out the back-end since using a view cell clears up the lag for you. Thank you for letting me know.
