### ISSUE TITLE
Craftable Items do no show in the Arcane Terminal

### ISSUE THREAD

**Issue by FatherOwnage** [Nividica/ThaumicEnergistics#202]
FTB Infinity v1.6.2 (Mod Pack)
AE2 rv2-stable-3
Thaumcraft-1.7.10-4.2.3.5
thaumicenergistics-0.8.10.5

As title says, I do not see AE2's craftable items while using the Arcane Terminal.
Even when switching the view to craftable only, nothing shows up.
This is only tested on a SMP server.

**Comment by Nividica** [comment]
See issue #112
