### ISSUE TITLE
Add a filtered essentia to Essentia Import/Export Buses using Crystallized Essentia

### ISSUE THREAD

**Issue by mdraves91** [Nividica/ThaumicEnergistics#203]
Right now it looks like you can only add a filtered aspect to the Essentia import and export buses using a Phial or Warded Jar. It would be nice to be able to use a Crystallized Essentia as well.

**Comment by Nividica** [comment]
The current acceptable items are phials, jars, and jar labels. I will add the crystallized version to the ToDo list.
