### ISSUE TITLE
Arcane terminal, search bar

### ISSUE THREAD

**Issue by Turmfalke2** [Nividica/ThaumicEnergistics#204]
hi,
When if I use an ME Crafting Terminal and drag and drop an item from the network into the crafting grid I can directly continue typing to search for the next item.
If I do the same in the Arcane terminal I have manually select the search field every time after I moved an item to the crafting grid.

Also for some strange reason I can't request items to be crafted from the Arcane terminal? Yes, I have the view mode turned to "Stored / Craftable"

**Comment by FatherOwnage** [comment]
Craftable items not showing up in the ACT is already known and being addressed in Issue#112: https://github.com/Nividica/ThaumicEnergistics/issues/112

Not sure about the search bar getting deselected  when clicking out of it. May been coded like that on purpose or not?

**Comment by Nividica** [comment]
I hadn't realized that some modes force the search bar to always be in focus.
Will get this corrected.
