### ISSUE TITLE
p2p not working with essentia?

### ISSUE THREAD

**Issue by Turmfalke2** [Nividica/ThaumicEnergistics#205]
hi,
I noticed I am unable to use an import bus to store essentia in drive on the other side of an p2p tunnel, I can reach items just fine, but it won't work with essentia.

**Comment by Nividica** [comment]
I can't imagine why this would be an issue, as all devices hand-off storage related requests to the network and let it figure out where to pull/push from.
I will do some testing to see if the recent changes I have made clear this up.

**Comment by Nividica** [comment]
Just did some testing and I have not been able to reproduce this issue. I may have incidentally fixed it during the backend overhaul. If this still occurs after I release 0.8.10.6 let me know.
