### ISSUE TITLE
Placing redstone card into an essentia import bus causes client to disconnect.

### ISSUE THREAD

**Issue by talonos2** [Nividica/ThaumicEnergistics#206]
Tested in a multiplayer environment. Putting a redstone card into an essentia import bus causes the client to immediately be booted, the error says "A fatal error has occured, this connection is terminated." Server continues running as normal, but contains this message:  

>[14:21:13] [Server thread/INFO]: Talonos lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

Thereafter, attempts to view (right click) the essentia import bus cause the client to crash again, a frame or two after displaying the GUI. The essentia import bus retains the redstone card even when wrenched off, and reattaching it and viewing it again also crashes.

There is a detailed stack trace left in the client's console. It's long so I put it on pastebin: http://pastebin.com/raw.php?i=byutEQUC

If you need any more info, let me know.

BTW: Thanks again for the iron gear fix. It's working great.

**Comment by Nividica** [comment]
Found the fix, was rather silly of me. But in the future one thing I can recommend for any device that takes upgrades, is that if an issue like this occurs you can break them with a pickaxe(or anything really) and it will reset the item and drop anything it contained.
