### ISSUE TITLE
Essentia Import and Export buses stop working after restart.

### ISSUE THREAD

**Issue by Yadokingu** [Nividica/ThaumicEnergistics#208]
After I restart my single player world import and export buses stop working. I have to remove the cables leading to them and then re-place them to fix the issue. 
That is especially a problem with the advanced alchemical furnice, since it will fill up with items, which will eventually despawn.

0.8.10.5

**Comment by Nividica** [comment]
The upcoming update may fix these issues as a massive under-the-hood overhaul is in the works. 
After 0.8.10.6 is released please let me know if these issues continue.

As for the advanced alchemical furnace, see #207
