### ISSUE TITLE
ACT and the NEI crafting tooltip

### ISSUE THREAD

**Issue by katzenpapst** [Nividica/ThaumicEnergistics#212]
When I look up a recipe in NEI and click the ? while in the arcane crafting terminal, the upper row of the recipe is cut off:

![te-nei](https://cloud.githubusercontent.com/assets/8077005/8560835/cd1d3e0e-251c-11e5-8ebc-283bfdb23cc6.png)

For arcane recipes, it doesn't work at all

**Comment by Nividica** [comment]
What version of NEI are you using? I am building against NEI-1.0.5.111

**Comment by katzenpapst** [comment]
I just updated to NEI 1.0.5.111+CodeChickenCore 1.0.7.46, but nothing changed. I also have neiaddons-1.12.10.33-mc1.7.10.jar, which I disabled, but again, no effect regarding this

**Comment by katzenpapst** [comment]
Found the culprit. It's RandomThings-2.2.4. It doesn't look like it's being supported for 1.7 anymore, but I guess I'll just try post it over there as well

**Comment by Nividica** [comment]
Closed because as far as I can tell there is nothing that I can do about to fix the issue. I tell NEI which gui is mine, and the positions of the slots, and it handles the item overlay.
