### ISSUE TITLE
ACT buttons lack rightclick to go backwards.

### ISSUE THREAD

**Issue by Ricewind1** [Nividica/ThaumicEnergistics#219]
Let me first say that I absolutely love this mod/add-on. Without it Thaumcraft would be terrible.

I've been working with Thaumcraft and Thaumic Energistics for a bit and I've ran into a few problems.
1. The Vis Relay Interface does not work. I've followed the instructions given by the Thaumonomicon. Scepters/Wands do not recharge in the Arcane Crafting Terminal. Not even on the same network segment, not even in the same chunk. (P2P bus was literally on the same cable piece as the terminal).
2. A few nuisances with the Arcane Crafting Terminal.
- The Terminal window does not re-size. It always has 3 rows regardless of the texture size. My AE2 Crafitng terminal has 6 rows currently while the Arcane still has 3.
- There is no "Search box mode". When entering the terminal you have to click the search box every time before you can start typing/searching. 
- You can't request items for crafting through the Arcane Terminal. None of the AE2 crafting recipes show up in the terminal. (When chancing "View" to "Craftable" nothing is shown while any AE2 terminal does show the recipes. 
- You can't right-click the buttons ("Sort By", "Sort Order", "View") to cycle backwards through the options.

The "Search box mode" issue also goes for the Essentia Terminal.

Once again, I love the mod and thanks for your work! (Maybe a future idea to integrate the entire infusion process into Thaumic Energistics)

**Comment by Nividica** [comment]
What version of ThE are you using? I added the search mode and resize buttons quite a while ago.
As for the craftable items see issue #112.
I will add support for rightclick to go backwards in the next release.

For the VRI:
It must be attached to the same network segment as the ACT
There must be an available channel
The relay crystal's base must rest against the VRI
Shift rightclick the VRI, not the crystal, to load settings, you will get a chat notification.
Rightclick the ACT to load settings, you will get a chat notification
The ACT and VRI both require network power to transfer vis

Thanks for the feedback ^.^

**Comment by Ricewind1** [comment]
I am using the following version of the mod:
thaumicenergistics-0.8.9.3a-rv2

As for the issue with the VRI, I've found out what I was doing wrong.
I forgot to turn the P2P bus into the actual VRI ><

The VRI DOES work cross-channel though.
It is currently transmitting c-vis to an ACT on the same cable as well as an ACT on a completely other cable coming from the controller)

**Comment by Nividica** [comment]
Ah, yeah that version is quite dated as it was released back in April. The latest version is 0.8.10.7 but I should be pushing out a new build soon with the first part of the new power system.

The VRI should function as long as both ends are on the same network segment, that is to say not separated by a sub-network boundary. As long as they are all part of the same network you can feed as many devices with digivis from a single source as you want.
