### ISSUE TITLE
Essentia Monitors facing wrong way on dense cables.

### ISSUE THREAD

**Issue by TimeDrawsNigh** [Nividica/ThaumicEnergistics#220]
We're using version 0.8.10.7 and having an issue with placing the essentia monitors as they face the wrong way (see image). They work fine with the regular ME cables.

![2015-07-21_23 02 11](https://cloud.githubusercontent.com/assets/13444849/8817094/f5262b32-2ffc-11e5-94d9-e03224bd9902.png)

**Comment by Nividica** [comment]
Both the storage and conversion monitors can only attach to non-dense cables. They treat the dense cable as-if it is a regular block and place accordingly.
