### ISSUE TITLE
ACT: Rightclick to craft as many as possible

### ISSUE THREAD

**Issue by katzenpapst** [Nividica/ThaumicEnergistics#221]
In the regular crafting terminal, you can put the crafting ingredients in place and then rightclick the product to craft as many items as you have resources for, up to one stack. Could you add that feature to the ACT as well?

**Comment by Nividica** [comment]
Its on the todo list, but way in the back. Last time this was included it caused items to disappear. For now your best course of action is the shift+leftclick.

See #139 for details on the issue.
