### ISSUE TITLE
Import and export cause bug

### ISSUE THREAD

**Issue by landerf** [Nividica/ThaumicEnergistics#225]
The export bus don't go on my AE cable, they channel go on and they skip on my cable. (4 Export on blank AE cable with 0 channel used and thez skip on :/ )

I'm french not english sorry.

**Comment by Nividica** [comment]
See #223

**Comment by landerf** [comment]
I put on ME smart cable fluix, and version is AE2 RV2

**Comment by Nividica** [comment]
Can you attach a screenshot?

**Comment by landerf** [comment]
![2015-07-31_00 36 56](https://cloud.githubusercontent.com/assets/13578936/8996951/9ada5da2-371c-11e5-824a-f8067cd4db17.png)
![2015-07-31_00 37 00](https://cloud.githubusercontent.com/assets/13578936/8996952/9adb2598-371c-11e5-8e5b-22b774390d02.png)

**Comment by landerf** [comment]
So p2p tunnel are link

**Comment by Nividica** [comment]
I'm not sure I understand the issue. It looks like the export buses are properly attached to the cable. The cable texture leads me to assume that there is not an ME controller on the network, are there more than 8 devices on the network? Also, does the network have power?
If you can, make the network tool(http://ae-mod.info/Network-Tool/), and right-click on the cable. It will list all attached devices and the current power state.

**Comment by Nividica** [comment]
Also, a screenshot of the network tool GUI would be helpful.

**Comment by landerf** [comment]
Yeah, i think it's just visual bug because on networking tool i can see :/
![2015-07-31_00 51 28](https://cloud.githubusercontent.com/assets/13578936/8997157/7a07f998-371e-11e5-9fa0-5fe2837a5403.png)

**Comment by Nividica** [comment]
Okay, whenever you are able too, try testing out a single export bus to see if it works.
Make sure there is essentia stored in the network, then set the export filter. It should begin filling up the adjacent warded jar. If it works as expected, then we can assume it is just a visual glitch.

**Comment by landerf** [comment]
Yes , the jar go fill, it's just a visual glitch but i fear don't works :/ thanks :)

**Comment by Nividica** [comment]
Anytime
