### ISSUE TITLE
Thaumic Tinkerer breaks CC integration

### ISSUE THREAD

**Issue by bacchussr** [Nividica/ThaumicEnergistics#228]
Wrapping the essentia provider returns a table containing the functions provided for essentia jars (maybe mirrors, too).  This only happens when Thaumic Tinkerer is installed.

**Comment by Nividica** [comment]
I will need to do some testing to try and figure this one out.

**Comment by Sayfog** [comment]
I think I know what's happening, TT automatically takes over any block with characteristics of an essentia tube/storage device (eg, the Essentia Provider).


https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/peripheral/PeripheralEssentiaTransport.java#L37

**Comment by nekosune** [comment]
This might be able to be fixed quite easilly, will add a black list that is accessible by IMC

**Comment by nekosune** [comment]
Aded an IMC accessible blacklist - https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/commit/f4060274d5aa3c9891733b95d0e2a2dee920bdc9

This should let you send a simple IMC containing the class name to blacklist to make TT ignore it

**Comment by Nividica** [comment]
I will leave this open until I can verify the fix is working when then next TT comes out.

**Comment by nekosune** [comment]
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/510/ should allow you to test, although as is it wont work, as modid is ThaumicTinkerer no spaces and unsure if getName and getCanonicalName differs
