### ISSUE TITLE
Arcane Assembler Ore Dictionary

### ISSUE THREAD

**Issue by Tergiver** [Nividica/ThaumicEnergistics#230]
I seem to remember reading that you fixed the problem of the Arcane Assembler using the Ore Dictionary which caused recipes with silverwood to work with any old wood. The fix seems to have been to globally remove ore dictionary use from the Assembler?

This is a problem for Ethereal Essence which now only crafts for the exact essence specified. Since they are used in storage components, it's quite inconvenient.

**Comment by Nividica** [comment]
I will have to come up with a way to figure out which recipes allow ore dictionary entries on which items, and which do not. I'm sure that info is somewhere in them, but worse case I will manually set those recipes which allow it.
