### ISSUE TITLE
OpenComputers Integration

### ISSUE THREAD

**Issue by brakhtus** [Nividica/ThaumicEnergistics#233]
Hello Nividica,
as you have already implemented a computercraft integration, would it be possible to also implement an integration for opencomputers?

greetings.

**Comment by XFactHD** [comment]
This is not really needed as OC can use CC peripherals when OpenPeripherals is installed.

**Comment by ruifung** [comment]
not without CC installed though? (I think)

**Comment by XFactHD** [comment]
That's right @ruifung

**Comment by Nividica** [comment]
As of this time I am not prepared to add support for any additional mods.
