### ISSUE TITLE
Warded Jar, Essentia Storage Bus, and Essentia Export Bus not working properly on occasions.

### ISSUE THREAD

**Issue by EtherealOnyx** [Nividica/ThaumicEnergistics#234]
When there is less than 64 (Warded Jar capacity) of essentia in a system, and you take some essentia out of a Warded Jar, the network will attempt to fill the jar. It seems to not realize when the jar is filled and will continuously drain from the system until it's no longer displayed. Updating the network refreshes the storage so it displays the essentia again, but then will continue to try and fill the warded jar until it drains to 0 again.
Both the Essentia Storage Bus and the Essentia Export Bus have the same aspect 'selected'.

Also, when the ME network resets (whether that's the chunk unloaded or out of power, etc),  the storage buses aren't actually showing the warded jars in the ME network until you update something on the network.

Mod Pack:
FTB Infinity 1.10.1

Mod Versions:
Thaumic Energistics 0.8.10.10
Thaumcraft 4.2.3.5
Applied Energistics 2 rv2-stable-10

**Comment by Nividica** [comment]
Can you provide the steps and minimal setup to reproduce this? I am not certain how you have your setup but I imagine something like:
Network -> Export Bus -> JarA
Network -> Storage Bus -> JarB
When you take from Jar A, via phial, the system will attempt to fill Jar A by draining Jar B.
I tried this setup, with and without storage cells containing the same essentia, and could not reproduce the issue.
