### ISSUE TITLE
Can't access stored essentia from a subnetwork

### ISSUE THREAD

**Issue by tiennou** [Nividica/ThaumicEnergistics#235]
It seems that Essentia providers don't work like AE interfaces w.r.t to providing access to stored "things".

I was trying to hack around #53 by building a "bunch" of Essentia level emitter/AE export bus w. crafting cards to drop the items in an Advanced Alchemical Furnace, but since that's `(Essentia types * 2)` channels => 4 dense cables I was planning on doing that in a subnetwork.

**Comment by ruifung** [comment]
Storage bus on standard ME interface.

**Comment by Nividica** [comment]
Answer provided by @ruifung
