### ISSUE TITLE
Applied Energistics rv3 Support?

### ISSUE THREAD

**Issue by AragurLP** [Nividica/ThaumicEnergistics#236]
Would it possible for you, to make support for Applied Energistics rv3?

**Comment by XFactHD** [comment]
Please read what is written on the download page for AE2 rv3. This version is still in alpha and might have some pretty bad bugs.

**Comment by crunkazcanbe** [comment]
From what I seen so far and I have been extensively using AE2 rv3 it runs better then all the other AE2 Versions I have tested it with many AE2 addons such as Extra Cells and ae2 stuff mods and both of those run really well with it ThaumicEnergistics is the only add-on that will not start with RV3 ,and I was also coming here to see if RV3 support could be added to this mod ? 



Thanx -Crunk

**Comment by XFactHD** [comment]
AE2 rv3 has big API changes and it might be that ThaumicEnergistics is using parts of the API that have changed while other add-ons are not using parts that changed.

This is what is written in the download section of AE2 rv3:
"Rv3 Alpha is not compatible with any AE2 add-ons, do not request add-on authors or other mod developers to support these builds."

**Comment by leagris** [comment]
Crash issue in [AEAspectRegister.java, line  \#571](https://github.com/Nividica/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/registries/AEAspectRegister.java#L571)

[crash-reports/crash-2015-10-10_22.55.16-server.txt](http://pastebin.com/4EeQHJba)

**Comment by Nividica** [comment]
Added rv3 support in build 0.9.0.0
http://minecraft.curseforge.com/projects/thaumic-energistics/files/2262329
