### ISSUE TITLE
Essentia Terminal power up problem

### ISSUE THREAD

**Issue by AT611** [Nividica/ThaumicEnergistics#237]
If the AE network runs out of power, then, after power is restored, the Essentia Terminal does not see any essentia stored in a ME drive (or probably does not see a whole ME drive by itself), until I wrench down the terminal and put it back on the cable.
Further experiments shown that If I power down only the ME drive, which stores an essentia, and then power it back up - everything works fine, so it's the Essentia Terminal who does not like to be powered down. Tested on a minimal setup of an Essentia Terminal, ME drive and an Energy Cell.

**Comment by Nividica** [comment]
I have not been able to reproduce this behavior.
Using the minimal setup you provided, plus a vibration chamber, I stored several essentia types on the network, allowed the power to run out, added coal to the chamber, power was restored, the terminal was instantly able to see everything on the drive.

**Comment by AT611** [comment]
Ok, I'll look into it. We have some addons for both Thaumcraft and AE, so it's probably one of them then. I didn't thought that any of them could interfere...

**Comment by Nividica** [comment]
The only specific thing that I know of that has been reported is the flat ME drives that Extra Cells provides. Last I checked, they caused odd out-of-sync issues.
Other than that, I can't think of anything that would be causing issue
