### ISSUE TITLE
I can't infusion craft the essentia provider or infusion provider please help

### ISSUE THREAD

**Issue by monsterhunterer** [Nividica/ThaumicEnergistics#238]
running the RR 3 modpack on AT launcher with a couple extra mods. I have tried everything from re installing to remaking my alter and updating the mod. it seems to start the process but wont take essentia or items and it just sits there blasting lightning and flux no matter how long I leave it. any ideas would be helpful and please tell me what info i need to give out for you to see to help me.

**Comment by Nividica** [comment]
Make sure you are using the correct cores, the essentia provider uses 1 of each, the infusion provider uses 2 of the coalescence.
Other than that, check all your ingredients, and make sure you have enough essentia.
