### ISSUE TITLE
Thaumic Tinkerer Blacklist

### ISSUE THREAD

**Issue by krejcar25** [Nividica/ThaumicEnergistics#241]
I really need to use coputercraft with ThaumicEnergistics to automate system refilling but can't now. I know it has been blacklisted in Thaumic Tinkerer in the latest 0.9.0.0 version but that requires EA rv3 doesn't it? and since I can't update AE to rv3 I can't use CC with this :( would it be possible to just bring a retro-update (something like 0.8.11) that would add nothing new but the blacklist?
(Or other way...can I manually blacklist it somewhere in config? I have no knowledge at all how this kind of blacklisting works)

**Comment by Nividica** [comment]
Unfortunately back-dating isn't feasible at this point. Sorry for the inconvenience.
