### ISSUE TITLE
AE/ThaumicEnergistics Issue 

### ISSUE THREAD

**Issue by ryuben** [Nividica/ThaumicEnergistics#242]
I cant see the total amount of essence in my AE system.

I have the drives and terminal i can see the essence in the Drives but when i Use the terminal - i see nothing.

If i have the terminal open when essentia is being added to the drives i can see what is added e.g. terra 1 but not the total amount.

its an issue with me i have had other people use my AE and they can see the essentia in the system fine - i just can't 
Help please

**Comment by krejcar25** [comment]
maybe a problem with security station? do you have one? if so, try removing it or reconfiguring your own card to have everything ;) not sure if that makes any diferrence though, just blind shot

**Comment by ryuben** [comment]
it is a public server - the issue "fixed" its self after the server was hard restarted

Not sure what the issue was but a restart of the server "fixed" it
