### ISSUE TITLE
Essentia storage not reliable with ME Drive Fixture from ExtraCells 2

### ISSUE THREAD

**Issue by TheChance** [Nividica/ThaumicEnergistics#243]
Might be an ExtraCells problem; this is my first foray into Thaumic Energistics.

After researching essentia storage, I crafted a 16k essentia storage drive, and threw it in an ME Drive Fixture on the same column as my terminals. I then placed an import bus adjacent to an alembic, and it sucked up 96 Arbor without issue - then stopped.

Nothing I did could persuade it to import any more Essentia, of Arbor or any other type. I spent quite a few minutes thinking something was wrong with my import bus or alembic placement before, on a hunch, swapping the ME Drive Fixture for a regular ME Drive.

Eureka! Working as intended now (and boy is it fun).

This may not be a serious issue, since ME Drives are *cheaper* than ME Drive Fixtures, but it's strange nonetheless.

**Comment by XFactHD** [comment]
ME drive fixtures are not fully implemented and heavily bugged.

**Comment by acidjazz** [comment]
Went nuts w/ this issue until I found this issue, possible to maybe not allow Essentia drives in the fixture until it's properly implemented? Save future cases of potential insanity?
