### ISSUE TITLE
Essentia Provider keeps disconnecting on server

### ISSUE THREAD

**Issue by Hazmatik** [Nividica/ThaumicEnergistics#244]
Everytime the server restarts or the chunk the essentia provider is in reloads I have to pick it up and place it again. The cable connecting to it is disconnected when this happens until I place it again.

**Comment by Nividica** [comment]
I will see if I can reproduce this.

**Comment by Nividica** [comment]
I have not been able to reproduce this with the latest dev build. I will post here once it goes live.

**Comment by Nividica** [comment]
Please try with the latest version and see if the issue still occurs: http://minecraft.curseforge.com/projects/thaumic-energistics/files/2272475

**Comment by Nividica** [comment]
Closing: Received no additional feedback.
