### ISSUE TITLE
[Duplication] Infinite Certus Quartz Wrenches

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Nividica/ThaumicEnergistics#248]
Use a Wand Focus: AE Wrench on a empty Thermal Expansion cache, and it will deposit a certus quartz wrench into that cache.

**Comment by Aquahatsche** [comment]
I can confirm this bug. In the code for the focus is a condition to ignore the using on TC's pedestals. This can be further improved to test for caches. If it is a cache just set player's sneaking to false. This will do the job and the cache rotates as expected. My testing code was:
```java
else if(te.getClass().getName().contains("Cache")) { 
			player.setSneaking(false);
		}
```

I think there could be something like a soft-dependency for TE, but I'm not experienced enough with forge yet.

**Comment by Nividica** [comment]
This damned wrench focus just keeps finding ways to dupe wrenches...
