### ISSUE TITLE
essentia import bus cant be prevented importing from arcane alembic.

### ISSUE THREAD

**Issue by convict999** [Nividica/ThaumicEnergistics#250]
ftb infinity latest version.

using thaumic redstone emitter onto essentia import bus to limit auram to be stored, with second output to a void jar via restricted tube.
The emitter will not work as expected with redstone card inserted in bus, placing a redstone torch adjacent fails to stop importing, as does a lever. 
I even tried a toggle latch between import bus and network (same block space as bus) essentia is still imported with toggle clearly offline (thought toggle only switched power, but every days a school day)
Waila doesnt show the import bus on/offline really doesnt help.

Im no coder but i imagine its more the alembic pushing into an available-ish? inventry, overriding the import bus control.

I resorted to using 2 warded jars one being a void, and controlling the import bus on bottom of standard warded jar as the essenta bus wont import from void jar. Is that intentional? or another gremlin?

Otherwise really enjoynig the reduced thaumcraft tedium, thanks to energistics. 
Thanks

**Comment by Nividica** [comment]
Hmm, it really should not function at all if it has no power. I will look into it and see why it is ignoring redstone and power.

**Comment by Nividica** [comment]
I have not been able to reproduce this in the latest dev build. Once I publish it I will let you know.

**Comment by Nividica** [comment]
Please try with the latest version and see if the issue still occurs: http://minecraft.curseforge.com/projects/thaumic-energistics/files/2272475

**Comment by Nividica** [comment]
Closing: Received no additional feedback.
