### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by ArcasCZ** [Nividica/ThaumicEnergistics#253]
http://pastebin.com/99Znp44a

Hello there :-) My friend told me, that he got game crash, so I'm sending you stacktrace :-) Hope you will fix it soon :-)

**Comment by Aquahatsche** [comment]
Hi there. I guess the network tool is disabled in the AE config file. I disabled it and I can reproduce the same stacktrace.

**Comment by ArcasCZ** [comment]
It happens when you click Arcane Assembler.

**Comment by Aquahatsche** [comment]
Yes. It should crash on all Thaumic Energistics network devices with GUI. There is no test for if the network tool is disabled and an error is thrown. Tomorrow I will commit a pull request. I do some further testing. (The network tool is not the only one you can disable...) 

If your friend can, he should just activate the network tool for now.

**Comment by ArcasCZ** [comment]
Can you send me source that you want to pull? I will compile it by myself and test it on server.

**Comment by Aquahatsche** [comment]
You can just clone my repo I think.

**Comment by ArcasCZ** [comment]
Thanks a lot :-)

**Comment by ArcasCZ** [comment]
When i tried to compile your source, I find out, what support of AE2 RV3 is wrong idea. Last RV3 doesn't work with this mod. So i think it's better to replace "List ... drops" row 634 of tileentities/TileArcaneAssembler.java "ArrayList ... drops" for now and put it back when AE2 author will bring AE2 RV3 Beta or stable.

**Comment by Aquahatsche** [comment]
You could just checkout the version 0.8.10.10 and add the changes I did. That is for AE rv2. I did that for my main world and it works like a charm.

**Comment by ArcasCZ** [comment]
I simly switched from List to ArrayList and it works. But - this AE2 works only on oldest RV3, newer RV3 versions throw errors.
