### ISSUE TITLE
Arcane Crafting Table Light Issues

### ISSUE THREAD

**Issue by Gettheball** [Nividica/ThaumicEnergistics#254]
Hey there, i finally found the correct way to contact you i guess, sry for the double posts in the forum and on curse tho. If you didnt read them, thats fine heres the issue again ;)

So theres a really small problem that really
drives me crazy. Its about the arcane crafting table and its light level.
The setup is quite simple. If i put a block behind the terminal its
getting darker. This goes even further the more blocks the terminal is
surrounded by. I tried a few things with the ME Conduits from Ender IO
and the Conduit Facades but this was getting me an even worse result.
With the Conduit Facades the Screen of the A.C.T was almost complete
black. Its working fine if you dont have any blocks around and stuff but
i wondered if this was intentional or just a compatibility bug in the
Infinity pack (2.2.2) im using. So i guess in comparison with the AE2 Terminals, the A.C.T is not lighting itself (generating light level?)

Just msg me for further Details
or try it out yourself. I really would appreciate any kind of
information if youre aware of this, working on it or if i just have to
deal with it. Everythings fine by me.

**Comment by Nividica** [comment]
I will try this out once I get the most recent issues patched and see if the problem persists

**Comment by Nividica** [comment]
My testing shows that the A.C.T.'s front panel fully illuminates when given power. In the attached screenshots I have it fully surrounded on all sides except the front.
![arcanetermoff](https://cloud.githubusercontent.com/assets/1585989/11999431/84f473f0-aa8b-11e5-8545-58c654518729.jpg)
![arcanetermon](https://cloud.githubusercontent.com/assets/1585989/11999430/84f3c478-aa8b-11e5-9f41-52794f037af9.jpg)

**Comment by Nividica** [comment]
Closing: Received no additional feedback.
