### ISSUE TITLE
Essentia Import/Export/Storage Buses won't interact with void jars

### ISSUE THREAD

**Issue by qidydl** [Nividica/ThaumicEnergistics#256]
I'm having a problem with Thaumic Energistics in the current FTB Infinity Evolved 2.2.2 pack, which appears to be Thaumic Energistics version 0.8.10.10. None of the essentia transfer mechanics seem to interact with regular Thaumcraft void jars. I can't get it to export essentia to a void jar with either an export bus or a storage bus, or see essentia already present in a void jar using a storage bus. I tried different sides of the jar, which didn't help, and the "Void Essentia?" button/option in the bus GUI didn't have any effect either. There are no problems interacting with regular jars or other blocks (e.g. alembics, alchemical constructs) that I can see; it's specific to void jars.

I also tried loading up an older world from a previous version of FTB Infinity (somewhere in the 1.x versions), which I had not played or touched in months, and I'm almost certain this used to work, because I had storage buses directly on void jars as part of a Thaumcraft setup that was running fine in the older version.

Is there any other information that might help diagnose this issue? Any ideas what might be going on?

**Comment by Aquahatsche** [comment]
#227 Have a look at this issue. In the newest version it should be fixed.

**Comment by Nividica** [comment]
Indeed the void jars were being ignored in 0.8.10.10. As @Aquahatsche mentioned, 0.9+ should resolve the issue.
