### ISSUE TITLE
[Bug][RV3]Opening Arcane Crafting Terminal crashes client

### ISSUE THREAD

**Issue by NEXUS2345** [Nividica/ThaumicEnergistics#258]
Crash log: http://pastebin.com/3f8ngKRM
For some reason, it only specifies this, I have attempted to reproduce this on multiple launchers.

Steps to reproduce: Place Arcane Crafting Terminal onto powered ME network and right click on it

Versions: Applied Energistics RV3 Alpha 13, Thaumcraft 4.2.3.5, Thaumic Energistics 0.9.0.0, Forge 1558

**Comment by Planetmind** [comment]
Hey, I'm here to hopefully provide some extra info on this issue.(Hi Nexus, it's Rasply!)

Ok, so first off, this crash also happens with the essentia terminal, not just the arcane crafting terminal. I tried using both terminal types with and without drives/essentia drives/essentia stored, with the same crash every time.

 I got a slice of client console logs from when the crashes occurred, and it seems to provide info that the crash reports don't. Should be the same versions of everything that Nexus provided as well.

Client log(I copy/pasted what seemed relevant):
http://pastebin.com/JxEQTL3h
And a crash report that doesn't seem to say anything useful:
http://pastebin.com/spMgqT8V

Hope this helps, and Merry Christmas!

**Comment by Nividica** [comment]
This has been fixed in the upcoming release. Ty for the reports.

**Comment by McMasterx** [comment]
Hi, don't know if it's a necropost or something, but I've encountered this issue today, and doing a bit of research led me to this post. Playing on a small 7 person server on Infinity Evolved Expert mode, and I'm the only one out of the 7 people that crashes when I open any UI from Thaumic Energistics.

**Comment by TSMooster** [comment]
I was having this same problem today.  I would instantly crash any time I tried to open an arcane crafting terminal or essentia terminal. Nobody else on the server seemed to have the same issue.  I fixed the problem by reinstalling and updating Java on my computer.  I installed both the 32 bit version for my browser and the 64 bit version for mine craft.  The problem went away.

**Comment by mrabenhorst** [comment]
Same thing for me, using Resonant Rise v3 Mainline. I tried updating AE2 rv3 5 to the most recent as well as TE 1.0.0.1 and reinstalled Java 8-77, nothing worked. Looks like a server error. 

Error here: http://pastebin.com/QarshRLG
