### ISSUE TITLE
[0.9.1.1] Server Crash on startup after updating to latest

### ISSUE THREAD

**Issue by Xiaminou** [Nividica/ThaumicEnergistics#261]
In modpack, server with a large world crashes on startup after updating to the latest AE2rv3 + TEs (from AE2rv2).
Compatibility issue with Ender IO's ME Conduit?

Crash Report: http://pastebin.com/SMYCk4bJ

**Comment by Nividica** [comment]
There was subtle name change from beta 1 to beta 2 with AE2-RV3, I just pushed the changes to the code base. They will be included with the next built.

**Comment by Xiaminou** [comment]
That was fast!
Does this means if I rollback to beta 1 it will work?

**Comment by Nividica** [comment]
It should yeah
