### ISSUE TITLE
[BUG] Arcane Crafting Terminal doesn't show Craftable Items

### ISSUE THREAD

**Issue by 1Darco1** [Nividica/ThaumicEnergistics#262]
**Description:**
When hooking up an ACT to my network, I am unable to request any craftable items through *vanilla* Applied Energistics 2. This is valid for both the setting "Stored / Craftable" and "Craftable". The terminal does not show crafting patterns (hooked up to Molecular Assemblers) nor Processing Patterns (hooked up to various Thermal Expansion and Mekanism machines).

**Mod Details:**
- Applied Energistics 2 RV2-STABLE-10
- Thaumic Energistics v0.8.10.7

**Additional Note:** I've not set up any thaumic automation yet, so I don't know about the Essentia Interface.

**Comment by Nividica** [comment]
Support for the ACT showing craftable items, and essentia automation is in the next build.
See #53 & #112

**Comment by 1Darco1** [comment]
Whoops. Should have also searched through closed issues. Sorry!

**Comment by Nividica** [comment]
No worries.
