### ISSUE TITLE
Crash on Load.

### ISSUE THREAD

**Issue by EndermanParty** [Nividica/ThaumicEnergistics#266]
I've had this crash every time I load with your mod. I've just been in too much of a rush to bother sending the report. I'm sure its something on my end rather than yours. Anyway, Help?

**Comment by EndermanParty** [comment]
Oops, forgot to post the link to crash. http://paste.ee/p/QS685 There you go.

**Comment by EndermanParty** [comment]
Also, using latest version. 1.0.0.0

**Comment by EndermanParty** [comment]
Turn.. There may still be an issue. Just not the one I sent you. So Sorry.

**Comment by Nividica** [comment]
Hmm, I am not sure what to make of that, as the method its complaining about not existing, most certainly exists.
Says that "appeng.api.definitions.IItemDefinition.isEnabled()" is missing, yet the beta-5 source code defines it here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/core/features/ItemDefinition.java#L66

The stack trace doesn't mention ThE, but have you tried without it?

**Comment by Nividica** [comment]
@_@ Ninja'd

**Comment by EndermanParty** [comment]
That was the first thing I tried. However Ae2 beta-5 did not work at all. Ill see about the beta-4. From what I gather this is an Ae2 issue not an issue from your mod. However if I can get beta-4 working WITH your mod ill let you know.
