### ISSUE TITLE
"Rendering Screen" Crash Inside Of Arcane Crafting Terminal

### ISSUE THREAD

**Issue by RoloEdits** [Nividica/ThaumicEnergistics#268]
I am getting this crash when bringing my cursor over any of the items in my AE System, its fine initially when opening the terminal and the cursor is over items, but if you hover outside of the inventory then bring it back it this happens. 

Crash Report: http://pastebin.com/CFM7B7ib

thaumicenergistics-0.8.10.10
Thaumcraft-1.7.10-4.2.3.5
appliedenergistics2-rv2-stable-10

**Comment by Nividica** [comment]
Hmm, a few questions:
* Does this happen with every item, or just AE parts?
* Does this happen in a AE2 crafting terminal?
* Is it possible for you to updated ThE?

In the crash log you posted "appeng.items.parts.ItemMultiPart" is crashing while trying to formulate it's tooltip, which is why I am curious about other items. But if possible I would recommend updating ThE to the latest version.

**Comment by RoloEdits** [comment]
Interesting, I tried hovering over different items to check and it seems to trigger on the disabled smart cable,  I have channels turned off, but its used in the quantum bridge recipe so I have them in my system. I am going to make a quick testing world to check this out more. Are there updates past 0.8.10.10 for rv2?

**Comment by Nividica** [comment]
Yeah 1.0.0.1 is backported to RV2, scroll down to addition files:
http://minecraft.curseforge.com/projects/thaumic-energistics/files/2277332

There was an issue on the AE2 tracker some time ago about disabled channels cause smart cables to be disabled improperly. It should be patched up in RV3.

If the item itself is causing the crash then updating won't fix the issue, as I did not plan accordingly for that situation. However I can put together a fix and upload it here for you to use, and add it to the official code base later.

**Comment by RoloEdits** [comment]
OK, I just checked and that seems to be it. And that would be great if you could :) though I hate for you to go out of your way to do that

**Comment by Nividica** [comment]
This is the most recent version + the tooltip check

https://drive.google.com/file/d/0B3XsROkASZNETnBWRU14eEtIUnc/view?usp=sharing

**Comment by Nividica** [comment]
Let me know if it gives you any trouble.

**Comment by RoloEdits** [comment]
Thanks a lot! It seems to have fixed it.

**Comment by Nividica** [comment]
Awesome, thanks for pointing this out ^.^
