### ISSUE TITLE
Libs

### ISSUE THREAD

**Issue by ArcasCZ** [Nividica/ThaumicEnergistics#271]
Update system is slow and when I need to fix something on server, I have to wait untill you push build or compile it myself. It's OK, but searching for libs is so awful. I don't even know which version of mods you use. Can you add folder libs to git as other developers do?

**Comment by nekosune** [comment]
Other developers dont add libs folder to git, but they do use maven, the trouble is Thaumcraft doesnt have a maven, nor does some others. Uploading the libs folder to git is basically uploading other's work.

**Comment by ArcasCZ** [comment]
Look at PeripheralsPlusPlus ;)

**Comment by Nividica** [comment]
I have include the libs I could into the build.gradle file. Outside of those you will need the latest 1.7.10 versions of Thaumcraft, Applied Energistics 2, COFH core, Mekanism, RotaryCraft, and maybe NEI, as I have always had trouble getting the .gradle version of it to work reliably in my dev environment.
Mekanism and RotaryCraft are needed to solve an "Incomplete Inheritance Hierarchy" error.

Including the lib folder itself would violate some terms and conditions relating to distribution rights, and while I could blindly ignore those, I won't. The best I could offer outside of the build file is to include a document that includes each mod's location of download.

**Comment by Nividica** [comment]
Front-page read me has been updated to include dependencies.

**Comment by ArcasCZ** [comment]
That's not solution -_- You still have to find which version is compatibile. Better is including URL to CurseForge AND exact version download. In ReadMe or in text file in project.

**Comment by nekosune** [comment]
@ArcasCZ  an example of something doing what it shouldn't, isnt an excuse for this one to do it

**Comment by ArcasCZ** [comment]
@nekosune It's not but - who gives care about this? :D

**Comment by nekosune** [comment]
Most people who actually care about the authors making these mods?

**Comment by ArcasCZ** [comment]
@nekosune I care about authors - but including libs is not reuploading these files in this way of meaning, 'cause you upload it for programing reasons, not for using in game - if you get me...

**Comment by XFactHD** [comment]
The law doesn't care about that, for the law reuploading others work for any possible intention means stealing others work.

**Comment by ArcasCZ** [comment]
@XFactHD And who will sue? :D

**Comment by XFactHD** [comment]
The creator of the mod you reuploaded. If he takes care of his mods or if he has an observant community, he will notice it and he could even make a DMCA take down request if he wants to go to the highest level. He has the right to do that as it is his work and not yours.

**Comment by ArcasCZ** [comment]
I sill don't see problem to include exact download link from CurseForge...

**Comment by XFactHD** [comment]
We aren't saying that including links to CurseForge is against the rights and conditions of distribution, we are still talking about uploading the files into the github repository.

**Comment by ArcasCZ** [comment]
@So why are not these links included?!

**Comment by lehjr** [comment]
Time spent updating exact links and continuing to address issues like this is time that could be better spent working on the mod itself. And the bottom line is that if you want to build any mod from the source instead of waiting for builds to pop up, then it's up to you to find everything you need. Yes, it's nice to have things in a maven so you don't have to worry about it, or even links to manually download the dependencies yourself, but no mod author is under any obligation to provide that for you. The fact that the mod is even opensource in the first place is a matter of convenience, not a right. Beyond that, some mods only have source in their repo, so no build.gradle or gradle wrapper. So at least be content with that.
