### ISSUE TITLE
Computer Craft Api is not Woking

### ISSUE THREAD

**Issue by r4dischen** [Nividica/ThaumicEnergistics#272]
The Api is not working like described in the Wiki.
Computer next to Essentia Provider only gives me
-isConnectable
-canInputFrom
-canOutputTo
-getSuctionType
-getSuctionAmount
-getEssntiaType
-getEssentiaAmount
-getMinimunSuction

for Infusion Provider
-getAspects
-getAspectCount

**Comment by Nividica** [comment]
See #228
