### ISSUE TITLE
WidgetAEItem::render item is unchecked.

### ISSUE THREAD

**Issue by iKaneki-Ken** [Nividica/ThaumicEnergistics#273]
http://pastebin.com/J045BS7G

**Comment by Nividica** [comment]
Do you by chance happen to know which mod adds that aspect?

**Comment by iKaneki-Ken** [comment]
I'll find out which mod adds it then report back.

**Comment by iKaneki-Ken** [comment]
The aspect comes from Avaritia as you said.
