### ISSUE TITLE
Crash when removing wand from ACT. wand deleted when re-entering game

### ISSUE THREAD

**Issue by djcosmic2** [Nividica/ThaumicEnergistics#276]
Game crashed when I went to remove my Shadow Embellished Warpwood Wand from Tainted Magic  equipped with a Time focus from the same wand. Upon reloading into the world, the wand was missing. http://pastebin.com/csFjrxXf

**Comment by Zsashas** [comment]
Have you tried the same actions with wands from vanilla Thaumcraft?

**Comment by charlesbevans** [comment]
I just had a crash while moving an amber wand with thaumium caps to the wand slot on the terminal. On reload my wand was gone. However, I was moving the wand without shift-clicking and I don't think I actually got the wand to the spot.
FTB Infinity Expert mode: 
[crash-2016-03-28_18.30.07-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/192719/crash-2016-03-28_18.30.07-client.txt)

**Comment by Nividica** [comment]
#274
