### ISSUE TITLE
Using the arcane terminal makes me crash in SMP

### ISSUE THREAD

**Issue by MrTubzy456** [Nividica/ThaumicEnergistics#279]
http://pastebin.com/8YW2daDC

All I'm doing is using the terminal to craft things. At first I was shift clicking on the question mark when looking at the recipe and that would make me crash. So I tried placing the items in one at a time and it still made me crash.

**Comment by KindarConrath** [comment]
Same issue as #274 I just bumped into the same issue.

**Comment by Nividica** [comment]
#274
