### ISSUE TITLE
Essentia Terminal view is overlayed by NEI

### ISSUE THREAD

**Issue by netzgeist** [Nividica/ThaumicEnergistics#281]
The Essentia terminal view is overlayed by NEI and therefore disturbing to use. I tended to disable NEI while using it but I guess its also worth a bug report.

Related Settings: 1680*1050, GUI size:  auto. 

Essentia terminal view is: http://i.imgur.com/1vPWOJx.png

Regular AE² crafting terminal view for reference: http://i.imgur.com/Vg1se4v.png

As a sidenote, the arcane crafting terminal does not have this issue as well.

**Comment by Nividica** [comment]
Honestly don't know how to go about fixing this one. Would need to look into NEI's API and see if there is a way to let it know when my GUI is taking up the screenspace.

**Comment by Nividica** [comment]
Was doing a lot of funky math in that GUI class for no reason. The issue ended up being that the GUI wasn't centered vertically.
