### ISSUE TITLE
Java reflection fails causing game to crash when loading

### ISSUE THREAD

**Issue by Dijkstra1** [Nividica/ThaumicEnergistics#282]
I am playing FTB infinity evolved it has recently been update with the newest version of Thaumic Energistics, and when I load my world it makes sever crash I even pull the world from the sever in singel player it makes the client crash then with same java reflection error, now new worlds are fine and seen people that have update with any issue but before the update they had not used any Thaumic Energistics, I do have, an arcane terminal, essentia terminal and to essentia storage drives in an ME drive of there own.

I have uploaded the crash reports from both my Minecraft server, and client, although i believe it same error on both.    

[crash-2016-03-01_21.58.24-server.txt](https://github.com/Nividica/ThaumicEnergistics/files/154435/crash-2016-03-01_21.58.24-server.txt)
[crash-2016-03-02_08.04.47-server client.txt](https://github.com/Nividica/ThaumicEnergistics/files/154436/crash-2016-03-02_08.04.47-server.client.txt)

**Comment by enterprise12nx** [comment]
Me too
http://pastebin.com/CJYuyi26

**Comment by Nividica** [comment]
It seems my parts are not Forge Multipart compatible.

**Comment by Nividica** [comment]
#300
