### ISSUE TITLE
Computercraft API is broken

### ISSUE THREAD

**Issue by netzgeist** [Nividica/ThaumicEnergistics#283]
Summary: 

You cannot wrap an essentia provider as a peripheral anymore. Your [demo script](http://pastebin.com/6D4axXj2) does not work as well. Its state will be "searching for peripheral" permanently. 

Env:
Infinity 2.3.5. That means: Forge 1558, TC 4.2.3.5(latest), TE 0.8.10.10(outdated, no fix in changelogs since then), AE2 rv2-stable-10(outdated, no fix in changelogs since then), OpenPeripheral Core/Addons 1.2.1 (Unknown if relevant for the bug)

**Comment by Nividica** [comment]
See if #228 is the root of the problem.
