### ISSUE TITLE
[Crash]  On loading region

### ISSUE THREAD

**Issue by Isolonice** [Nividica/ThaumicEnergistics#285]
Hello, when some players log in the server it crash

Mod version: thaumicenergistics-1.0.0.1.jar
Crash log: http://pastebin.com/Ws1X0qcm

We removed the block but still crashing: http://pastebin.com/XDh24VFj

Someone got it too (not sure that's the same)
http://forum.feed-the-beast.com/threads/2-3-3-2-4-2-thaumic-energistics-server-crash-on-world-load-thepartbase-ispowered.148477/

@Robotia said that this code could solve the problem:

http://pastebin.com/tD7rC2tt

**Comment by QORTEC** [comment]
I too have this issue; [OpenEye](http://openeye.openmods.info/crashes/70a9481b0525953af7284580db63046f).

Let us know if you need additional information.

**Comment by KaneHart** [comment]
I'm also having this issue.

**Comment by Nividica** [comment]
See #282
