### ISSUE TITLE
Crash on crafting storage cells in Arcane Crafting Terminal

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [Nividica/ThaumicEnergistics#286]
Hello,
When I try to craft either a standard AE2 storage cell, or a Thaumic Energistics essentia storage cell in the Arcane Crafting Terminal, my game crashes. It happens in either singleplayer or multiplayer.

Crash log: http://pastebin.com/gPJ5Qf8p
Let me know if I need to supply anything else

**Comment by charlesbevans** [comment]
Just happened with a 16k essentia storage cell. FTB Infinity Evolved expert, recommended version (2.4.2). This happened whether I crafted the cell directly or crafted a housing and storage component separately. Crafting the empty housing didn't cause a crash.

**Comment by Lohoydo** [comment]
Can confirm with 64k essentia storage cell in an arcane terminal.  Has happened multiple times.  I have not tried in a regular arcane crafting table.

[crash-2016-04-14_08.25.59-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/219176/crash-2016-04-14_08.25.59-client.txt)

**Comment by Nividica** [comment]
See #274
