### ISSUE TITLE
Research Name List

### ISSUE THREAD

**Issue by NicolaRavani** [Nividica/ThaumicEnergistics#287]
Hey dearest Modmaker,

I got a Worldcrash because of Microblock + Smart Cable + Thaumic Crafting Terminal/Essentia Storage and had to remove ThaumicEnergistics from my World in order to remove the microblocks and Cables.

After adding back the mod I lost all related researches obviously. I tried to add them via the /tc commands but i cant figure out the "real" names.
I dug into your code, but I am sadly not able to find the names. Could you pretty please post a list with all the names for each research?

Thank you so much, if not for the list, then for sure for this awesome mod!

**Comment by NicolaRavani** [comment]
Found them... /tc research list  is your friend (casesensitiv):

- Vibration Chamber  `thaumicenergistics.TEESSVIBCMBR`
- Quartz Duplication  `thaumicenergistics.TECERTUSDUPE` 
- Arcane Crafting Terminal  `thaumicenergistics.TEARCANETERM`
- Arcane Assembler  `thaumicenergistics.TEARCANEASSEMBLER`
- Infusion Provider  `thaumicenergistics.TEINFPROV`
- Wand Focus: AE Wrench `thaumicenergistics.TEFOCUSWRENCH`
- Thaumium Gear Box  `thaumicenergistics.TETHAUMGBOX`
- Vis Relay Interface  `thaumicenergistics.TEVISINT`
- Digi Sentia Storage  `thaumicenergistics.TESTORAGE`
- Knowledge Inscriber  `thaumicenergistics.TEKNOWLEDGEINSCRIBER`
- Golem Wifi Backpack  `thaumicenergistics.TEGOLEMWIFIBACKPACK`
- Iron Gear Box  `thaumicenergistics.TEIRONGEARBOX`
- Distillation Pattern Encoder  `thaumicenergistics.TEDISTILLATIONPATTERNENCODER`
- Essentia Monitoring  `thaumicenergistics.TEESSTERM`
- Essentia Provider  `thaumicenergistics.TEESSPROV`

/closed

**Comment by Nividica** [comment]
Good lord, I had no idea that all my research names would be so... long. I intended for them to just be "TE<name>".
