### ISSUE TITLE
Unable to partition cells in the essentia workbench

### ISSUE THREAD

**Issue by AryuSyrius** [Nividica/ThaumicEnergistics#288]
I insert an empty cell into the workbench. Insert a phial of the essentia I want to partition. Press the partition button. At this point, if I hover over the cell while it is still in the workbench, the tooltip reads "partitioned". As soon as I remove it, the partitioned goes away. When inserted into a drive, all type of essentia are written to the cell.

Forge Mod Loader;7.10.99.99
Minecraft Forge;10.13.4.1614
Thaumic Energistics Core;0.10.0.0 
Thaumcraft;4.2.3.5

**Comment by Nividica** [comment]
Will try this and see what happens.

**Comment by Nividica** [comment]
I can not confirm this behavior, everything is working as expected on my end.
If the problem persists after the next release let me know.
