### ISSUE TITLE
Thaumic Energistics increases Metallum on Iron Nuggets

### ISSUE THREAD

**Issue by rndmorris** [Nividica/ThaumicEnergistics#289]
Vanilla Thaumcraft iron nuggets have a Metallum value of 1.  Installing TE increases that value to 4, and removing it reverts it to 1.  Allowing nuggets to have such a high Metallum value allows one to produce an infinite number of iron nuggets with Thaumcraft's alchemy system.

Mods installed:
- Applied Energistics
- Thaumcraft (and Baubles)
- Thaumic Energistics

I have tested this on a fresh installation of both forge and all three mods listed above, to no effect.

**Comment by Nividica** [comment]
ThE should not be touching iron nuggets. Will look into this.

**Comment by Nividica** [comment]
Confirmed
