### ISSUE TITLE
Arcane assembler fails to craft Advanced Alchemical Construct

### ISSUE THREAD

**Issue by emperor06** [Nividica/ThaumicEnergistics#292]
I have set the recipe for the advanced alchemical construct on my knowledge core and arcane assembler. When I try to autocraft it, the crafting processor GUI crashes. That's the GUI that shows the required components (the one that pops just after you choose the quantity).

Crash:
The GUI starts popping up and immediately closes. I get the following message on the game chat:
`Error: java.util.concurrent.ExecutionException:
  java.lang.IllegalStateException:
  java.security.InvalidParameterException: World is null.`

There is nothing in the logs and the game itself doesn't crash (the exception is obviously handled).
Note that so far, all other recipes I have made work perfectly. For example, the essentia valve (that also requires a chain crafting) works.

Forge: 10.13.4.1558
AE2: RV3-beta5
Thaumic Energistics: 1.0.0.1

**Comment by Nividica** [comment]
Confirmed

**Comment by Nividica** [comment]
Turns out it is a bug in the AE code, I was able to work around it however.

**Comment by Nividica** [comment]
Discovered #299
