### ISSUE TITLE
Essentia level emitter stops working bug + steps to reproduce

### ISSUE THREAD

**Issue by Tonlim** [Nividica/ThaumicEnergistics#293]
probably related to #209 

### mods used
![mod versions](https://cloud.githubusercontent.com/assets/7755814/14290731/8a73eb0a-fb60-11e5-9e97-30d0544fffb0.PNG)

### issue
When placing a forge microblock (tested with "oak wood planks cover") in the same block as an essentia level emitter, the emitter stops working. It still shows it is active using the pink color, but doesn't emit redstone particles and/or signal.  
When the microblock is removed, the emitter is still broken. It also becomes impossible to open the GUI of the emitter in 1.0.0.1. However in 0.8.10.10 (the version in Agrarian Skies 2) the GUI still opens and seems to work normally.  
WAILA also doesn't show the "device online" tooltip anymore.

I've also tested the "essentia import bus" and the "essentia export bus". Those work just fine.

### reproduction
* get working setup
![working](https://cloud.githubusercontent.com/assets/7755814/14292186/3ef036d2-fb67-11e5-95e8-ba25eca1cb9b.png)
* place a forge microblock in the same block -> breaks emitter
![microblockadded](https://cloud.githubusercontent.com/assets/7755814/14292216/668a1370-fb67-11e5-8082-d59d2f573278.png)
* remove the microblock -> emitter still broken
![microblockremoved](https://cloud.githubusercontent.com/assets/7755814/14292253/97de34b0-fb67-11e5-835d-61874723deb2.png)

**Comment by Nividica** [comment]
May be related to #282, as it seems my parts are not multipart compatible. Somehow.

**Comment by Nividica** [comment]
#300

**Comment by Nividica** [comment]
Think I figured this one out, completely missed a method I needed to override "canConnectRedstone", its a wonder it ever worked at all.
