### ISSUE TITLE
Client crash when using Arcane Terminal

### ISSUE THREAD

**Issue by spannerman79** [Nividica/ThaumicEnergistics#296]
OpenEye report http://openeye.openmods.info/crashes/72ad09e4917ba924358bd6dd0d08a7d5

Forge 1614
MC 1.7.10
TE: thaumicenergistics-1.0.0.1.jar
AE2: appliedenergistics2-rv3-beta-5.jar
Thaumcraft: Thaumcraft-1.7.10-4.2.3.5.jar

Causes crash to desktop on usage - not all the time though.

[crash-2016-04-11_01.28.08-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/211828/crash-2016-04-11_01.28.08-client.txt)

**Comment by Nividica** [comment]
See #274
