### ISSUE TITLE
Builds failing due to 403 on dependency

### ISSUE THREAD

**Issue by NEXUS2345** [Nividica/ThaumicEnergistics#301]
We are attempting to build the newest commits on Jenkins, but unfortunately libraries.minecraft.net is not cooperating: http://pastebin.com/GfAxhhR4

Any help would be appreciated.

**Comment by Nividica** [comment]
It looks like the chicken chunks maven repo is either down or gone. To work around it, download any missing jars and add them to the libraries folder. The exact versions I have are as follows:
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar

**Comment by NEXUS2345** [comment]
The issue stems from the WAILA maven repo. I added those jars to the libraries folder and they still failed.

**Comment by Nividica** [comment]
Once you have the jars in place, remove it from the buildscript so that it will stop trying to download them.

**Comment by NEXUS2345** [comment]
The issue is that the WAILA dependency is trying to download them, not ThaumicEnergistics itself, could you suggest the line to remove from the build.gradle?

**Comment by Nividica** [comment]
compile "mcp.mobius.waila:Waila:1.5.10_1.7.10"
