### ISSUE TITLE
Crash - java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Esctogrillo** [Nividica/ThaumicEnergistics#306]
Crash report (server): http://pastebin.com/GmyE5ZTH
How to reproduce: SunDuan, player from my server, said is when he change armor on Arcane Terminal, but I don't know if It's correct.
Crash server and client.

**Comment by Nividica** [comment]
See #300.
Your ThE is out of date, "thaumicenergistics{1.0.0.1} [Thaumic Energistics]", please try again with the [latest version 1.0.0.5](http://minecraft.curseforge.com/projects/thaumic-energistics/files/2295264)
