### ISSUE TITLE
AE2 wireless terminal not charging in "project ozone"

### ISSUE THREAD

**Issue by bojosos** [Nividica/ThaumicEnergistics#307]
I had a wyvern flux capacitor which had 80 million rf in it and the wireless just sucked all of the power almost instantly but it didn't charge. I put it in the security terminal and it didn't charge there either

**Comment by Nividica** [comment]
To my knowledge the security terminal doesn't charge wireless terminals, however I have not tried. The only charging method I personally test is the AE2 charger, as I have no other mods in my build environment that provide charging facilities. The wyvern flux capacitor is from Draconic Evolution I believe, I will do a test with it later and see whats up.

**Comment by Nividica** [comment]
I have just tested this and it working as expected. The wireless terminal is charged, and the Wyvern Flux Capacitor is slightly drained. What version of Thaumic Energistics & Applied Energistics are you using?
I can also confirm that the security terminal does not charge wireless terminals.
