### ISSUE TITLE
Instant crash with RV2 version

### ISSUE THREAD

**Issue by Zsashas** [Nividica/ThaumicEnergistics#308]
Crashes instantly upon loading the instance.

https://gist.github.com/Zsashas/0e443b71f310539472512ee4505b8a37

**Comment by Nividica** [comment]
Java 7 is not supported, please upgrade to Java 8 and try again.

> Java path is:
C:/Program Files/Java/jre7/bin/javaw.exe

**Comment by Zsashas** [comment]
But I have java 8 already, and specified it. It used it before updating...

**Comment by Nividica** [comment]
According to the log:

> [16:03:40] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_67, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre7

You may want to double check your launch options and see if something has defaulted back to Java 7.

**Comment by Zsashas** [comment]
Yeah, looks like something did that. Will make a new issue if anything else happens.
