### ISSUE TITLE
Random crash at Arcane Crafting Terminal

### ISSUE THREAD

**Issue by kostanakis** [Nividica/ThaumicEnergistics#312]
It crashes with NPE randomly, when I try to get the product of craft.

Crash log: https://gist.github.com/kostanakis/de62d5631d247b95ab9e6f106f40369e

**Comment by Nividica** [comment]
Please update to the latest version of ThE, 1.0.0.5
Related to #274

**Comment by Nividica** [comment]
If you can't update, a work-around is to place empty view cells in all of the view cell slots. Since they are empty they have no effect, and since they are there the terminal shouldn't cause a null crash.
