### ISSUE TITLE
Old Dupe is not fixed

### ISSUE THREAD

**Issue by BlayzerQ** [Nividica/ThaumicEnergistics#313]
On Arcane Crafting Terminal:
If fast use Right Click & Left Click - item on mouse will duplicates.

**Comment by linkinkov** [comment]
Same problem, its too much easy dupe

**Comment by Eufranio** [comment]
It's fixed here, using AE2 rv3-beta-6 and 1.0.0.5.

**Comment by BlayzerQ** [comment]
It's not fixed. I`am using AE2 rv3-beta-6 and 1.0.0.5.

**Comment by Eufranio** [comment]
Lol

**Comment by JasonMcRay** [comment]
I can confirm this bug as well in InfiTech 2 modpack. Quickly pressing Right and Left mouse button dupes the clicked item by 1/2.

The right mouse buttom must be held down when clicking the left button:
Exact step: Press RMB and hold it > press LMB whilst still holding RMB. (Also works if Both RMB and LMB are pressed at same time)

Here is a video of said procedure: https://youtu.be/KH_ekeUDJJw

**Comment by Eufranio** [comment]
Sorry, really dupes, i was testing with the crafting grid slots.
@Nividica, is there a workaround or a fix?

**Comment by BlayzerQ** [comment]
Hey! Dupe will fixed?

**Comment by forsco** [comment]
Hi,

This dupe is still current. With the Arcane Crafting Terminal open where you see all of your stored items pick one you want to test the dupe on. Right click on that item and then very quickly left click. Selected item has now been duped.

With the Forge Microblocks crash bug fixed this is the last remaining bug afaik so that the Terminal can be unbanned from our server for players to use.

Any update would be appreciated.

**Comment by cthulchu** [comment]
and no feedback in half a year... nice.

**Comment by Kagenokami** [comment]
Bumping this. I really hope the mod author comes back to fix this...if he cares about his user base he will. Automating anything for thaum is impossible in a server until this dupe bug is fixed...

**Comment by Nividica** [comment]
I decided to dust off the old dev environment and see if I could not track down this issue.
The good news is that I found it. Now I just have to remember how to get it built and uploaded.

For those interested as to what the problem was check the commit for more details
