### ISSUE TITLE
Storage bus does not remember negative priority

### ISSUE THREAD

**Issue by createdAnAccountJustForThis** [Nividica/ThaumicEnergistics#316]
When logging in and out in single player, the essentia storage bus changes a negative priority back to 0. It also did not seem to be giving it the negative priority even when it was displayed. Tested with an essentia reservoir and a labelled void jar.

**Comment by Nividica** [comment]
I am fairly certain I coded in a check to not allow priority to be negative. It never occurred to me that the network would support a negative value, nor that anyone would have a use for a negative.

**Comment by PaluMacil** [comment]
I think the main use for negative is to ensure it's lower than new storage blocks. I used it, but I don't recall if I still am.
