### ISSUE TITLE
essentia terminal, essentia storage bus/essentia export bus issue

### ISSUE THREAD

**Issue by Felkey** [Nividica/ThaumicEnergistics#318]
i have essentia storage and export buses (the storage buses wont export the essentia so i need both in order to keep track of inventory and export) hooked up to each jar for every type (55 in total). it is also hooked up to a drive bay with multiple 64k essentia drives. for id say about 95% it works great. however, if between the drives and the jars (both void and standard) there is less than 64 of any type of essentia it does not calculate correctly on the essentia terminal. for example, if there is 20 praecantatio, the essentia terminal will rapidly change between 16-24 or a range similar to that (might be 18-22) and the numbers always change in intervals of 2. its not a major issue as the exports and everything still work and the count is correct is there is 64 or more of a particular essentia. 

thank you for any insight you have into this issue (ps it has yet to crash after a couple hours or so there are not crash logs i can attach to this), i tried looking through past issues and didnt see anything exactly like this, sorry if i missed it

**Comment by Nividica** [comment]
I imagine this is your issue:
Storage bus reports that there is XYZ type of Essentia in the network.
Next tick: export bus asks if there is XYZ type of Essentia in the network, it is informed there is. It then asks for that Essentia. The storage bus responds and draws Essentia out of the jar and places it on the network on its way to the export bus. 
Next tick: Export bus receives Essentia, and places it into the jar.
Next tick: the storage bus notices the Essentia amount has changed and reports there is Essentia of type XYZ in the network....

It sounds like the storage bus and export bus are caught in an endless loop of taking Essentia from a jar and depositing it back in the same jar a few ticks later. This will cause rapid changes to the amounts, and the jar will may never be completely full. There is no way to avoid this situation when exporting to a jar that is watched by a storage bus on the same network, as the network does not care where things come from, nor where they are going, only how much of something is available.

**Comment by Felkey** [comment]
thank you for the response, not really game breaking so its not really a big deal

could i ask another question, is there a way to turn off importing via an interface, or make it so the storage bus can do the job of the export bus so that way the system can avoid the confusion?

btw, love this addon mod, i just started messing around with a it a few weeks ago and its quickly become one of my favorites to mess around with

**Comment by cleverca22** [comment]
Logistics pipes doesn't have a similar issue, it has a safety to ensure the source and destination cant be the same block

**Comment by Felkey** [comment]
as in mekanism logistics pipes? if so is that a suggestion that i use them or a suggestion for future versions of the mods in which case ill stop talking?
