### ISSUE TITLE
[Crash] Invalid ID (no config option avaiable)

### ISSUE THREAD

**Issue by ParaMotor** [Nividica/ThaumicEnergistics#319]
I'm using Forge 10.13.4.1614, Thaumcraft 4.2.3.5, ae2 rv3-beta-6 and Thaumic Energistics 1.0.0.5

http://pastebin.com/MzPmgdFt

Seems like this crash is caused combined with Relocation or MCFrames. I disabled the rest of the errored mods and it still crashes.

**Comment by Nividica** [comment]
'Invalid id 6992 - **maximum id range exceeded.**'
There is no more room in the registry for blocks.
A quick google search yielded this: http://www.minecraftforge.net/forum/index.php?topic=27908.0
