### ISSUE TITLE
Essentia storage does not work with an ME chest.

### ISSUE THREAD

**Issue by AllenKll** [Nividica/ThaumicEnergistics#320]
Creating an Essentia storage cell, and placing it in an ME chest does not allow input or output of essentia.  

When putting a storage cell with Essentia already in it, in the chest, the interface does not show any contents.  I tried putting an Essentia Terminal on the chest, and still is shows no stored essentia and allows no adding of essentia.

**Comment by Sorbe** [comment]
Try powering the chest with AE energy (not RF energy as it seems to only want 80/80 RF).
When I did that, the top of the chest shows the essentia contents and lets me add/remove essentia.

**Comment by AllenKll** [comment]
I swapped the TE Hardened energy cell for an AE2 Creative energy cell and that seemed to work.  I'm playing Blightfall Mod pack, and have no way to generate AE2 power reliably or efficiently, but it is interesting that this experiment worked.

I thought maybe this is an issue with the ME chest, but I tried a normal storage cell and that works just fine on RF.

**Comment by Nividica** [comment]
Weird. I wouldn't expect the source of power to have any bearing on if the cell works or not, unless its simply not getting enough power. Does a creative TE cell work?

**Comment by AllenKll** [comment]
Did some testing.  A TE Creative energy cell does not work either.  

If I pass the RF though an energy accepter to the chest it does work.  But I guess that kind of makes sense as the accepter is turning RF into AE.

It's still odd that the chest will work with direct RF and a normal storage cell, but not an essentia one.
