### ISSUE TITLE
Essentia provider - crafting of essentia?

### ISSUE THREAD

**Issue by jaspervdm** [Nividica/ThaumicEnergistics#321]
Hello, I am currently using Thaumic Energistics in FTB IE:S and am really enjoying it. However, I have an issue.

Using the distillation pattern encoder, I have set up a system that allows me to request basically all essentia types via the essentia terminal.

In addition I have a essentia provider hooked up to an alchemical construct. If I have enough of the required essentia in the system for a specific recipe, it works perfectly fine. However, if some essentia is missing, I noticed that the provider does not request it from the autocraft system. Is this intended behaviour, or am I missing something?

If this feature does not exist, I could of course always make a system with essentia level emitters to always have a certain amount of each type of essentia in the system, but that would require a lot of channels, which I'd rather avoid.

Thanks for the help!

**Comment by codewarrior0** [comment]
Was looking for this feature today and couldn't seem to find it. :+1: for autocrafting essentia.

**Comment by Hazmatik** [comment]
I was wondering about this as well, without the ability for the essentia provider to autocraft or an essentia export bus to accept a crafting card to autocraft it basically makes the distillation pattern encoder almost worthless. Cause as the OP stated could just set up an export bus with essentia level emitter to make sure you always have a certain amount in the system.

**Comment by Nividica** [comment]
This stems from essentia being stored as a fluid, and the crafting sub-system working only with items. I could not find a way to link those two together so that during a sub-craft if you did not have enough essentia it would add that to the crafting catalog. The best I also came up with was using essentia level emitters or computer craft to control the amount in the system.
