### ISSUE TITLE
Feature Request: Prevent substitutions in arcane assembler recipes

### ISSUE THREAD

**Issue by Hazmatik** [Nividica/ThaumicEnergistics#325]
The issue I'm having is I set a pattern in the arcane assembler to craft essentia storage components with an essence of a specific aspect yet when I tell the system to craft them it just uses whatever kind of essence it wants to in the recipe despite having plenty of the type I programmed the recipe with. Problem being my wisp farm generates tons and tons of the primal aspects essence but very few of the compound aspects essence and the arcane assembler seems to like to use all the compound essences that I would rather have for essentia.

**Comment by Nividica** [comment]
Sounds like this is related to the Ore Dictionary, unfortunately I never came up with a way to allow fine-grain control over which items can be used with the oredict and which could not.
