### ISSUE TITLE
Inter Mod Bug - Energistics + Thaumic Horizons

### ISSUE THREAD

**Issue by blacksythe** [Nividica/ThaumicEnergistics#326]
When supplying a curative vat from thaumic horizons using an essentia provider during an infusion, it continues to draw the same aspect until that aspect is completely drained from the AE2 network before moving onto the next aspect.

I have also posted this in the Thaumic Horizons git in case this issue is not relating to Energistics

**Comment by Nividica** [comment]
The provider only does as its name suggests, provides essentia. If something continues asking for it, it will continue providing it as shown here:

```java
	public int takeEssentia( final Aspect aspect, final int amount, final ForgeDirection side )
	{
		// Extract essentia from the network, and return the amount extracted
		return this.extractEssentiaFromNetwork( aspect, amount, false );
	}
```
