### ISSUE TITLE
[1.7.10] Client Crash loading TE

### ISSUE THREAD

**Issue by Morpheus1101** [Nividica/ThaumicEnergistics#327]
cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/List;

Crash log @ https://puu.sh/tS1Rg/212575759f.txt

Pack info @ https://mods.curse.com/modpacks/minecraft/243125-arduous

**Comment by Nividica** [comment]
Your AE is rv-3, but your ThE is rv-2. Use the rv-3 realease.

**Comment by Morpheus1101** [comment]
Ahh, yes, that would indeed be it, lil confusing since it shows mod needs updating.

**Comment by Walkman100** [comment]
I've just ran into this error, took me a while to figure out there are two different 1.0.0.5 versions of Thaumic Energistics, and the file marked as latest on CurseForge is for RV2 while I was using RV3.
