### ISSUE TITLE
Inter Mod Bug - Thaumic Energistics + Wireless Crafting Terminal (Golem Backpack)

### ISSUE THREAD

**Issue by badungu** [Nividica/ThaumicEnergistics#328]
I have both Thaumic Energistics and Wireless Crafting Terminal installed, I wanted to try the Wifi Backpack functionality, the problem is, that the player can't put the backpack on a golem...
I tried to look at the save files and found out, that the NBT_ENCRYPTION_KEY should be "wifiKey", but the Wireless Crafting Terminal mod only sets it to "Key", it's okay for me to set the NBT_ENCRYPTION_KEY manually in the save, but I think you should know about it.... :)

Also reported it on the Wireless Crafting Terminal git. :)

**Comment by Nividica** [comment]
It sounds like the API methods
```java
public void setEncryptionKey( final ItemStack stack, final String encKey, final String name )
public String getEncryptionKey( final ItemStack stack )
```
are not being called, but rather the mod is directly working NBT data.
