### ISSUE TITLE
Infusion Provider API not recognizing essentia in stored ME Network

### ISSUE THREAD

**Issue by andythorntonjr** [Nividica/ThaumicEnergistics#329]
I'm not sure if this is a resurfacing of issue #228 or not, but it seems somewhat similar. When attempting to utilize the Computercraft API to getAspects() from an Infusion Provider, the system does not recognize any essentia in the network (empty list). The API works fine for jars, but it comes back with no results on the provider. The network itself does contain multiple essentia at different amounts and the provider works for Infusion of items via the Thaumcraft Altar. 

Current Mod versions: 

Applied Energistics2-rv3-beta-6
ComputerCraft1.75
OpenBlocks-1.7.10-1.6
OpenModsLib-1.7.10-0.10
OpenPeripheralAddons-1.7.10-0.6
OpenPeripheralCore-1.7.10-1.4
OpenPeripheralIntergration-1.7.10-0.6
ThaumicTinkerer-2.5-1.7.10-163
Thaumicenergistics-1.0.0.5
Thaumcraft-1.7.10-4.2.3.5

(can list any additional mod versions, but think these are the primary ones that could affect things. I've updated most mods to the latest 1.7.10 Minecraft versions.)

**Comment by Nividica** [comment]
It is very possible that one of the other mods is also providing an interface for CC, and mine is being overwrote. Not much I can do about that unfortunately.
