### ISSUE TITLE
Playing 1.7.10 and mod crashes the pack

### ISSUE THREAD

**Issue by Senorloanshark** [Nividica/ThaumicEnergistics#330]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.features.IInscriberRegistry.getRecipes()Ljava/util/List;

I went through the effort of looking through the logs and this mod is the only one causing an error

**Comment by TheGoldenProof** [comment]
I'm getting this same exact problem. I'm pretty new to this crash report reading but it seems like the only thing I can think of that would cause this is either it depends on another mod or there's a version incompatibility. I could be wrong.

**Comment by cjmlax** [comment]
I am also receiving a crash either from this or from Applied Energistics.
[crash-2017-11-14_12.57.31-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/1477198/crash-2017-11-14_12.57.31-client.txt)

**Comment by Nividica** [comment]
Yes, the issue is using the RV-2 version of ThE with RV-3 of AE2
@TheGoldenProof 
(Line 105) appliedenergistics2{rv3-beta-6}
(Line 371) thaumicenergistics{1.0.0.5-RV2}
