### ISSUE TITLE
Essentia Provider not providing?

### ISSUE THREAD

**Issue by InterPlay02** [Nividica/ThaumicEnergistics#331]
Hi!

First of all: Great mod, you have here!
I'm here to tell you something that maybe is an issue, or a bug...
The essentia provider maybe is not working with the Curative Vat, from Thaimc Horizons. It works fine with the alchemical construct.
There are plans for making it work fine?
**And, if this is happening only with me, there is some one that can tell me what should I do to fix this?**

I'm using Applied Energistics rev3 + Thaumcraft 4 + Thaumic Horizons + Thaumic Energistics rev3...

Thanks...

**Comment by InterPlay02** [comment]
I mean: it is not providing the essentia.

**Comment by Nividica** [comment]
I would suggest trying to put a tube between the provider and the vat. However as noted in issue #326 , the vat may continue to draw essentia out of the network even if it does not need it.
