### ISSUE TITLE
Distillation Pattern Encoder not recognizing Meto or Perfodio

### ISSUE THREAD

**Issue by mtjohnson47** [Nividica/ThaumicEnergistics#332]
When putting hoes, shears, and pickaxes into the distillation Pattern Encode, it does not show Meto or Perfodio.  I can't figure out any other source for auto-crafting these.

Playing the Infinity Evolved modpack

**Comment by samperlmutter** [comment]
Yeah, I just came across this issue too. I'm playing the 1.7.10 pack from the technic launcher.
