### ISSUE TITLE
Can't use partially damaged tools when crafting

### ISSUE THREAD

**Issue by Fapiko** [Nividica/ThaumicEnergistics#333]
Recipes that have been modified to require tools that take durability damage, such as GregTech tools, look for the specific durability tool used in the recipe. This means that in order to automate those recipes, I need to set it to use max durability tools and have it craft a fresh version of the tool each time.

The stock AE pattern terminal has an Ore-Dict substitutions button that will work around this - it would be nice if the Knowledge Enscriber supported that as well.

**Comment by Nividica** [comment]
Interesting, I have ore dictionary enabled for my crafting recipes. Would need to look into meta/damage value checks as well to ensure they are not preventing use of damaged items.
