### ISSUE TITLE
Distillation Pattern Encoder dont recognize essentia crystals and ethereal essences aspects

### ISSUE THREAD

**Issue by TheThingG** [Nividica/ThaumicEnergistics#335]
MC 1.7.10, Thaumic Energistics 1.0.0.5 AE2-RV3

When i tried to make system, that convert crystals back to essentia i find this bug.
![essence_crystal_corpus](https://user-images.githubusercontent.com/5640217/35633607-b264de14-06ba-11e8-94ad-572df345ac2f.PNG)

Also distilation pattern for ethereal essences is broken too. It doesn't see main aspect, only two Auram.
![etheral_essence](https://user-images.githubusercontent.com/5640217/35633700-f2aef7a2-06ba-11e8-8f35-a2eb3c9725d1.PNG)

**Comment by Nividica** [comment]
#332
