### ISSUE TITLE
TE/Thaumic Horizons Vat issues

### ISSUE THREAD

**Issue by Xlaits** [Nividica/ThaumicEnergistics#338]
After some tinkering with my system, a once working set of providers on cables completely stopped working. All of my Storage and MEnet stuff are on Cyan cabling, Thaumic stuff on Magenta cabling.

Using Thaumic Horizons' Curative Vat, I have made MANY many abominations using an essentia provider, but suddenly, the two providers on THAT set of magenta cables have stopped seeing the drives that store my essentia, confirmed by placing an Essentia Terminal on that set of cables, which turns up a blank screen. Using a wireless terminal and placing an Essential Terminal on another color cable, I can then see the drives again.

None of the cables are overloaded, none of the cables are crossed, there's power, there's connections, there's channels. It does take an abnormally long time for any devices to get a channel on those cables, and the server window IS giving an error, provided in an image below. That error repeats CONSTANTLY.
![unknown](https://user-images.githubusercontent.com/32484365/37635685-86d99030-2bd3-11e8-982b-86f3857c8b6b.png)

**Comment by Xlaits** [comment]
So, when an Essentia Provider is connected to the network, ALL AUTO-CRAFTING is unable to function properly.

**Comment by Nividica** [comment]
For the error spam, the two bits I picked up on are
* at thaumcraft.common.entities.ai.interact.AIUseItem.click
* at net.mcft.copy.betterstorage.tile.entity.TileEntityLocker.OnBlockActivated

Which looks like their is a golum that is clicking on a locker, and its causing the error spam

---

I honestly do not know what is causing the network to fail on all auto-crafting nor able to see the storage. 
As I have not been able to reproduce the issue. My question is: If you create a new creative world, does it happen there as well?

My best guess would be that the network has fragmented, and while your network is physically connected, internally its two(or more) networks, which you can look at with the network tool.

As to why I think that might be the case is that every network device (cables, blocks) when first placed, or first loaded, have their own tiny 1 block network. It then checks its neighbors, and if it finds another network, those two networks merge into one network. [As specified here.](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv3-1.7.10/src/api/java/appeng/api/networking/IGridCache.java#L83)

If something was to fail consistently during this merger, you would end up with two networks, even with cables/block touching. Now, I would expect there to be some kind of warning in the log, but I dont know that for sure, and with the spam it would be hard to find in the log.

With the network tool you can see all devices that are registered on a network. I suggest using one to examine your network and see if there are any devices missing. If there are, start at that device and work your way back towards your controller, checking each cable/block along the way until you find the break.

**Comment by Xlaits** [comment]
From what I have tested, everything behaves as it should in a new world. I will try setting up the cables and THEN adding the devices first. The devices behave just fine while on their own network, which I have them set up on for right now. However, this does not fully explain why the Infusion Provider still works (despite needing to physically move drives around).

I have indeed tried my best to break all the cabling and re-add them to the network, but we're moving those machines anyway, so I'll have a chance to re-do the cables. I will return with results.

**Comment by Xlaits** [comment]
So, I've tested putting it on a separate network, and that indeed works, but when I re-added them to the main network, everything stopped working again. It's JUST the essentia providers that have stopped working. I have no errors in the logs, either.

**Comment by Nividica** [comment]
Hmm, I am at a loss as to whats up. To really dig into it I would need your save and what mods your using. It almost sounds like the grid is locking up when you connect the essentia provider.

I could make a custom build and throw in a bunch of logs so you can examine whats happening, but that would be kind of pain for you.

**Comment by Xlaits** [comment]
If you would like, I could pack up the server and send you the current build of it.

**Comment by Nividica** [comment]
That works for me

**Comment by Xlaits** [comment]
Alright, give me some time to upload it to MEGA, and I'll give you the link.

**Comment by Xlaits** [comment]
Apparently, that's going to take about half an hour for the upload. If you want, I also have a VNC server running on that machine, if you want to look at the machine's copy itself while we're waiting.

**Comment by Nividica** [comment]
Hmm, without being able to attach a debugger I am not sure there is much I could do. I will need to step through the process of grid creation and try to find where it is failing.

**Comment by Xlaits** [comment]
You'll have full control, you can do whatever needs to be done. No one is logged on at the moment, and I don't mind doing whatever needs to be done to either a) get this problem solved or b) help others. It's all up to you, I'll just set the password to the VNC server to something else temporarily.

**Comment by Nividica** [comment]
How goes the upload?

**Comment by Xlaits** [comment]
Right here:

https://mega.nz/#!pJ4QFDDK!sPPyXXxo1Ym7jG-tH1Ul8ihfnZ5hPxLO6S3aDtndo9g

**Comment by Nividica** [comment]
Sweet, got it downloaded, I will start digging in and post when I have an update

**Comment by Xlaits** [comment]
Thank you! If you need anything else, lemme know.

**Comment by Xlaits** [comment]
It's a private/public server, really meant for just a close group of friends. It is public with no whitelist, so if you'd like to take a look, the server's address is xlaitsnet.ddns.net. If you need OP, let me know your MC handle, and I'll give you OP for testing.

That is interesting, and I'm still a Big Reactors newbie, so I'm still learning the ropes. The spread out network is kind of required in our set up, since we're doing a communal server setup, and I am the *only* one who adds or removes things from the network, so the others on the server won't notice the load time of new devices...  at least until my other players try to learn AE2... which one of them kinda is planning on that. 

Something I did notice recently is that the Essentia Provider attached to the automated alchemy system IS pulling the essentia TO itself, but it is not feeding it to the object requesting the essentia...
