### ISSUE TITLE
Arcane Crafting terminal [1.7.10]

### ISSUE THREAD

**Issue by HeberonYT** [Nividica/ThaumicEnergistics#340]
https://www.youtube.com/watch?v=thpp5-FyBtY

thaumicenergistics-1.1.2.0
appliedenergistics2-rv3-beta-6

**Comment by Nividica** [comment]
That video is well over a year old. Are you still having dupe issues?

**Comment by HeberonYT** [comment]
Yes, I mentioned above the versions of the mod with which the problem happens.
