### ISSUE TITLE
Vis Relay Interface depends on actual block rather than capability

### ISSUE THREAD

**Issue by AnrDaemon** [Nividica/ThaumicEnergistics#341]
The research and the recipe of a Vis Relay Interface makes it very inconvenient for modpacks that have ME P2P Tunnel disabled.
I understand the need to have the capability enabled, but having to enable specific unrelated blocks is just wrong.

**Comment by Nividica** [comment]
Disabling P2P buses?! Madness lol.
P2P forms the backbone of my AE networks, I wouldn't have considered that it would ever be, or even could be, disabled.
I can likely detect that it is disabled during recipe creation, however I would need a replacement recipe. Do you have any suggestions as to what the recipe should be?

**Comment by AnrDaemon** [comment]
I would very much like to see it its own block, like ME Wireless AP, but since it's "a little bit" too late… How about this?
```
mods.thaumcraft.Arcane.removeRecipe(<thaumicenergistics:part.base:6>);
mods.thaumcraft.Arcane.addShaped("thaumicenergistics.TEVISINT", <thaumicenergistics:part.base:6>, "aqua 2, ordo 2, ignis 2, perditio 2, terra 2, aer 2",
  [
    [<ore:crystalFluix>, <Thaumcraft:ItemShard:6>, <ore:crystalFluix>],
    [<ore:ingotIron>, <appliedenergistics2:item.ItemMultiMaterial:24>, <ore:ingotIron>]
  ]
);
```
http://prntscr.com/jl4uo2

P.S.
Is it normal that vis tunnel does not use channels?

P.P.S.
With only 2-blocks controller, you have 320 channels to play with. Plentiful, IMO.

**Comment by AnrDaemon** [comment]
BTW, do you create your own P2P tunnel or use ME one?
