### ISSUE TITLE
No essentia provider in JEI/research

### ISSUE THREAD

**Issue by Docanis** [Nividica/ThaumicEnergistics#363]
i cannot seem to see the Essentia provider in the energistics research category, and i have 100% completed in it.

It is not present in JEI either. Is this something anyone has seen before, or is my modpack just bugged?

**Comment by BrockWS** [comment]
Do you have Infusion researched? The provider research should be located between the Digi-Sentia and Essentia Buses iirc.

**Comment by Docanis** [comment]
I have a infusion provider, but that is only for the infusion crafting.

When i look on the Wiki a Essentia provider block is also mentioned, that is used for the Thaumatorium.

I opened up a creative single player world and unlocked all research, but i can still only see the infusion provider.

Does this block serve both purposes now?

**Comment by BrockWS** [comment]
Ah my bad, the wiki is outdated since for 1.12.2 there was a complete rewrite so not everything has been implemented. The Infusion Provider can be used for the Thaumatorium by using the [Emptying/Filling Essentia Transfuser](https://ftb.gamepedia.com/Emptying_Essentia_Transfuser_(Thaumcraft_6)) on the provider and Thaumatorium. Eventually I will be renaming the block and making sure it can work in all situations.

**Comment by Docanis** [comment]
Thanks for the very fast reply!

Makes sense to just have one block for both.

For infusion im guessing it does not need the emptying/filling essentia transfusers?

**Comment by Docanis** [comment]
Did i misunderstand what you wrote?

The thaumatorium does not want to draw essentia 

http://prntscr.com/mk5iqb
http://prntscr.com/mk5jat
http://prntscr.com/mk5ji0

**Comment by Docanis** [comment]
Where do i post a bug report? Its a minor one, but when you place the infusion provider on top of a cable it does not connect before the cable is put there again.

**Comment by Docanis** [comment]
I tested and i only need to use the emptying transfuser on the thaumatorium, then the infusion provider flows essentia to those :)
