### ISSUE TITLE
Breaking an arcane crafting terminal delete the upgrade (arcane charging)

### ISSUE THREAD

**Issue by Saereth** [Nividica/ThaumicEnergistics#364]
Version: 2.1.1

**Comment by IRSmoh** [comment]
Actually, in general anything stored in the internal inventory of the "Arcane Crafting Terminal" does not drop on breaking. Breakage source does not matter (tested with a pickaxe, tested with a ae2 wrench).

**Comment by BrockWS** [comment]
Sorry for the delay, should be fixed in the next update.

**Comment by BrockWS** [comment]
Please let me know if the issue is fixed.
https://minecraft.curseforge.com/projects/thaumic-energistics/files/2683500

**Comment by IRSmoh** [comment]
yep that fixed it but a new bugs in now. I'll just make a new issue lul
