### ISSUE TITLE
arcane terminal does not scale with GUI size settings

### ISSUE THREAD

**Issue by IRSmoh** [Nividica/ThaumicEnergistics#365]
on "normal" graphics setting:
![image](https://user-images.githubusercontent.com/2626462/53822574-9bba3880-3f35-11e9-80fc-d81d4e079c20.png)

"large"
![image](https://user-images.githubusercontent.com/2626462/53822674-d328e500-3f35-11e9-969a-ffac158e3b2f.png)

"small"
![image](https://user-images.githubusercontent.com/2626462/53822761-fc497580-3f35-11e9-890a-3cffc6a88ffd.png)

vs default crafting terminal:

![image](https://user-images.githubusercontent.com/2626462/53822726-ec319600-3f35-11e9-8246-db154cc480df.png)

![image](https://user-images.githubusercontent.com/2626462/53822706-e045d400-3f35-11e9-8eb4-2a132921eed8.png)

![image](https://user-images.githubusercontent.com/2626462/53822772-02d7ed00-3f36-11e9-89bf-e087a2523c54.png)

**Comment by IRSmoh** [comment]
looks like it works with
`
        # Valid values:
        # TALL
        # FULL
        # SMALL
        S:"Terminal Style"=FULL
`
default given to new users is "TALL"
>why thats even an option I don't know

**Comment by BrockWS** [comment]
I forgot to fix this before I released 2.2.0. Will fix in the next release.
