### ISSUE TITLE
Crash when crafting arcane bellows

### ISSUE THREAD

**Issue by jounihh** [Nividica/ThaumicEnergistics#368]
I'm on ftb ultimate reloaded 1.4.0
![image](https://user-images.githubusercontent.com/40239267/54754579-7ba09f80-4bec-11e9-9489-23c8cd8ec563.png)
![image](https://user-images.githubusercontent.com/40239267/54754599-89562500-4bec-11e9-98be-c5c05bc0d47b.png)
When i click this button the game crashes
![image](https://user-images.githubusercontent.com/40239267/54754637-a25ed600-4bec-11e9-8531-677db4137c36.png)

**Comment by BrockWS** [comment]
Please provide the crashlog and latest.log. Upload them to a paste service like pastebin or gist.

**Comment by jounihh** [comment]
[latest.log](https://github.com/Nividica/ThaumicEnergistics/files/2992300/latest.log)
the game doesn't crash it just freezes and says not responding

**Comment by jounihh** [comment]
ok this time i got this screen
![image](https://user-images.githubusercontent.com/40239267/54758255-79424380-4bf4-11e9-9f8b-547278097bfa.png)
[latest.log](https://github.com/Nividica/ThaumicEnergistics/files/2992412/latest.log)

**Comment by BrockWS** [comment]
Should be fixed in the next version
