### ISSUE TITLE
[Feature request] Arcane Terminal

### ISSUE THREAD

**Issue by niklas2233** [Nividica/ThaumicEnergistics#370]
Hey so i dont know why or how the vis crystal works but can you make it so they stay when you use the plus in jei and when you press the store items button. 

I would also like to add the ability to change the search mode like on the regular terminals.

**Comment by BrockWS** [comment]
You can change the search mode in the terminal, make sure you are running the latest version.

The clearing of vis crystals is intended, if there is more demand I might consider adding a config option instead.

**Comment by niklas2233** [comment]
could you add that as a config? that would be really nice

**Comment by niklas2233** [comment]
where is the search button http://prntscr.com/nh7h7x

**Comment by BrockWS** [comment]
![image](https://user-images.githubusercontent.com/2309747/56809828-22293180-6878-11e9-804a-557d678aba23.png)

**Comment by niklas2233** [comment]
![ladda ned](https://user-images.githubusercontent.com/33903786/56810424-904d0480-6836-11e9-88e6-fb8caa57fd5b.png)

**Comment by BrockWS** [comment]
Oh yes my bad. Not yet implemented but i'll eventually get around to it (hopefully for 2.3.0).
