### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by niklas2233** [Nividica/ThaumicEnergistics#372]
hey im getting this crash when i open the arcane terminal and search for great wood

https://pastebin.com/aFY5rMJk
[crash-2019-04-23_16.51.42-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/3108143/crash-2019-04-23_16.51.42-client.txt)

**Comment by BrockWS** [comment]
Looks like an issue with Forestry leaves. See ForestryMC/ForestryMC#2336.
