### ISSUE TITLE
Dummy Aspect shows in JEI

### ISSUE THREAD

**Issue by wewannaown** [Nividica/ThaumicEnergistics#381]
**Describe the bug**
When going into JEI searching for "@thaumic" to get all thaumic stuff shown up, it shows "Error Report to mod dev" when going with the mouse over an empty field. Its ID is thaumicenergistics:dummy_aspect

**Screenshots**

![15629489925486270593872220133544](https://user-images.githubusercontent.com/20926386/61143643-10e4de00-a4d3-11e9-92df-83fc964e8ae3.jpg)

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 
 - Applied Energistics: 
 - Thaumcraft: 
 - Thaumic Energistics: 
 - Modpack: FTB Ultimate Reloaded

**Additional context**
I don't know the versions of each stuff
But I assume it to be the most recent depending on latest FTB Ultimate Reloaded. Currently playing on my Server with this modpack.

**Comment by BrockWS** [comment]
Yes, I had forgotten to hide it in JEI. Should be fixed in the next version.
