### ISSUE TITLE
GUIs not correctly blocking other actions

### ISSUE THREAD

**Issue by swoolcock** [Nividica/ThaumicEnergistics#389]
**Describe the bug**
`Part`s' `onActivate` is returning false on client-side, which means that other client events can trigger.  This is obvious when holding a block, as a ghost block will place in front of the part temporarily.  It's even more obvious when playing on a server, since books will still open (Thauminomicon, etc.)

**Steps to Reproduce**
1. Hold a block and right click on any part from Thaumic Energistics (Arcane Terminal, Export Bus, etc.)

**Expected behavior**
Client actions are blocked before opening the GUI (obvious as the punching animation will play).

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2838
 - Applied Energistics: rv6-stable-7

Versions as at commit: https://github.com/Nividica/ThaumicEnergistics/commit/199c73a0d7b19415df74abf40b4b4528cce607f1

**Comment by Nividica** [comment]
Stepping out of the shadows for a brief moment to accept this, and your other PR, and push out a build. Thank you for helping out :D
