### ISSUE TITLE
Instant client disconnect from Arcane Terminal (AE2-RV6, TE2.2.4)

### ISSUE THREAD

**Issue by bepri** [Nividica/ThaumicEnergistics#395]
Upon opening the Arcane Terminal, like any other AE2 terminal, there's a brief lag on the first open where all the slots are grey as the terminal (I assume?) scans all the cells on the network. I've got a pretty big network currently - around 60-80 64k cells, 40 64k fluid cells and a number of terminals and one quantum link - so the scale might add to the crash. I'm not sure. But within about a second of opening and seeing this greyed-out interface, my client instantly disconnects.

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2847
 - Applied Energistics: RV6 stable 7
 - Thaumcraft: 6
 - Thaumic Energistics: 2.2.4
 - Modpack: Enigmatica 2

**Additional context**
Thaumic Energistics is not an inherent feature of this modpack, I added it to my server's files and my own client manually, but everything else seems to be fine with the mod. The ME Essentia Terminal doesn't crash me at all.

**Logs/Crashlogs**
The console for my server simply says:
[18:33:44] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: bepri lost connection: Disconnected
[18:33:44] [Server thread/INFO] [minecraft/DedicatedServer]: bepri left the game
My client says:
Connection Lost - A fatal error has occurred, this connection is terminated

I can't find any relevant actual crashlog files, I'm not actually sure where to look for that. But I'll gladly replicate the bug and then grab the log file if you know where to look.

**Comment by orin999** [comment]
I have the same issue now that just started.  The terminal worked for some time.  
Version Information

Minecraft: 1.12.2
Forge: 14.23.5.2847
Applied Energistics: RV6 stable 7
Thaumcraft: 6
Thaumic Energistics: 2.2.4
Modpack: FTB Universe 1.1.1

**Additional context**
In the same save if I create a barebones AE2 network the terminal opens without issue but once connected back to my main system is causes crash.

[crash-2020-11-27_15.02.58-client.txt](https://github.com/Nividica/ThaumicEnergistics/files/5609725/crash-2020-11-27_15.02.58-client.txt)

**Comment by bepri** [comment]
Closing this to clean out my issues - this looks abandoned and likely not gonna get resolved.
