### ISSUE TITLE
Open arcane crafting terminal "A fatal error has occurred, this connection is terminated"

### ISSUE THREAD

**Issue by Gavin123-code** [Nividica/ThaumicEnergistics#402]
**Describe the bug**

**Steps to Reproduce**
IDK MAN IM NOT A GENIUS!

**Expected behavior**
the arcane terminal opens normally?
**Screenshots**

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2855
 - Applied Energistics: rv6-stable-7
 - Thaumcraft: 6.1.BETA26
 - Thaumic Energistics: 2.2.4
 - Modpack:N/A (normal forge install)

**Additional context**
Not Required. Add any other context about the problem here.

**Logs/Crashlogs**
https://pastebin.com/uMsmtRnP

**Comment by Gavin123-code** [comment]
I think its a render issue because EVERY TIME IT OCCURRS IT HAPPENS RIGHT WHEN ITEMS START RENDERING

**Comment by 811Alex** [comment]
You're meant to fill the report. This is not nearly enough info to help you. What even makes you think this is related to this particular mod?

**Comment by 811Alex** [comment]
The error seems to be related to WirelessFluidTerminal. There could be an incompatibility with that. Perhaps they haven't written the mod with ThE in mind. I'd try testing without that mod first and if it works fine without it, then go from there.

**Comment by Gavin123-code** [comment]
ok

**Comment by Gavin123-code** [comment]
but did u even read the "RENDER ISSUE" thing?

**Comment by Gavin123-code** [comment]
> You're meant to fill the report. This is not nearly enough info to help you. What even makes you think this is related to this particular mod?

dont know what youre talking about arcane crafting terminal is from this mod correct?

**Comment by Gavin123-code** [comment]
nope nothing after removing WFT

**Comment by 811Alex** [comment]
no errors or no change?

**Comment by Gavin123-code** [comment]
> **Describe the bug** A clear and concise description of what the bug is. I open the arcane crafting terminal my server crashes
> 
> **Steps to Reproduce** Steps to reproduce the behavior: IDK MAN IM NOT A GENIUS!
> 
> **Expected behavior** A clear and concise description of what you expected to happen. the arcane terminal opens normally? **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Version Information**
> 
> * Minecraft: 1.12.2
> * Forge: 14.23.5.2855
> * Applied Energistics: rv6-stable-7
> * Thaumcraft: 6.1.BETA26
> * Thaumic Energistics: 2.2.4
> * Modpack:N/A (normal forge install)
> 
> **Additional context** Not Required. Add any other context about the problem here.
> 
> **Logs/Crashlogs** https://pastebin.com/uMsmtRnP

**Comment by Gavin123-code** [comment]
> no errors or no change?

i meant i still have the issue.

**Comment by 811Alex** [comment]
Can you send your new log after removing it?

**Comment by Gavin123-code** [comment]
[latest.log](https://github.com/Nividica/ThaumicEnergistics/files/7420056/latest.log)

**Comment by 811Alex** [comment]
ok, a few questions:
- did the error happen today or 2 days ago? the crashlog you initially provided is from 2021-10-24 14:33:50 EDT, would that be when you saw that error?
- have I understood correctly that you're running a dedicated server and it crashed when you saw the error?
- if it's a server that crashed, are your logs/crashlogs from the server or the client?

**Comment by Gavin123-code** [comment]
crashlogs:server
dedicated server:no
time:yesterday

**Comment by 811Alex** [comment]
Right... so it's a server but not dedicated server? what is it, a second game open to lan?
and again, are you sure the crashlog you provided is from the time you saw the error and not earlier?

**Comment by Gavin123-code** [comment]
no whenever you close a forge world on 1.12.2 it says shutting down internal server so i think whats happening is theres a server but not open to the public per se

**Comment by Gavin123-code** [comment]
still there?

**Comment by 811Alex** [comment]
Yeah. So, the game does indeed have an internal server that it uses when you're in single player. But basically when people ask if you're using a server they mean a separate server from your game.
Also, a crash is when it completely closes after an error, so I'm guessing you won't find a crash log for this. Assuming the "latest" log you provided does include the error you're reporting, I think I see the issue, but I don't know what caused it.
For a bug to be fixed, it has to be reproducible in the development environment, so it can be studied better. For this issue, this is not the case for most installations, so it's either related to the mods you're running or related to your world.

Does it happen every single time you open the arcane terminal?
Does it happen in a new world (can be creative), that has a simple ME system with just a couple of items?

**Comment by Gavin123-code** [comment]
only happens in my world called ayo a new world is just fine maybe i have way too many items

**Comment by Gavin123-code** [comment]
i think its beyond fixing

**Comment by Gavin123-code** [comment]
i have 5 million fluix crystals i dont know why

**Comment by 811Alex** [comment]
Yeah, world specific issues would be nice to fix, but it's hard without the world. Idk if it's the amount of items or a specific item or w/e, sadly.
