### ISSUE TITLE
Ability to autocraft essentia

### ISSUE THREAD

**Issue by MichaelRalston** [Nividica/ThaumicEnergistics#53]
I really want to be able to automate centrifuging and the alchemical furnace, so that I can say something like "Get me 64 Humanus essentia" and my big AE autocrafting system will craft up crafting tables, burn those in the furnace to get Fabrico, then run the Fabrico through the centrifuge to make Humanus. (admittedly, the uncertainty of the centrifuge would make this unreliable, but that's fine.)

The existing AE system almost works for this - I can use ME Interfaces to put things into the furnace, but I can't say what the output is in a processing recipe because I can't specify that it gives essentia.

Likewise, while with this I can *almost* automate alchemy (I can say that for instance one iron nugget gives multiple iron nuggets in an automated alchemy thing that I have hand-setup), I can't say the essentia requirements so that the autocrafting will know to make them in the alchemical furnace.

**Comment by Nividica** [comment]
I have a new idea I will try to implement to approach this.

**Comment by Nividica** [comment]
Unfortunately it looks like to support this I will need to write my own 'crafting' sub-system which will watch for the return of essentia. I will continue to look for a way to pull this off.

**Comment by generilisk** [comment]
It's a roundabout way, but a workaround could be to crystalize it so the crystal shows back up in the system, then re-melt the crystals.

**Comment by Nividica** [comment]
I have been working on this most of the night, and after doing some deep, deep digging into AE2's crafting system I came up with a way to do this. My testing so far has been promising but I still have quite a few checks to work out and I have -no- idea how it will react to sub-networking yet.

Ultimately I had to create a new item that represents essentia, however this item will never be stored anywhere. I effectively lie to a crafting CPU and say that the 'item' has been delivered when the essentia has been imported. The only draw-back is that I won't be able to hide the patterns from regular item terminals. You will see the aspect and can craft it, but it will not be stored after the craft.

If all goes as I plan it, you will create essentia patterns in a new block/gui. They will be stored on standard pattern item. You will place these in interfaces just like regular patterns. From there the crafting system will handle requests.

However I am faced with an issue, most items produce multiple aspects, and if there are two patterns that both produce a certain aspect I do not know which one the crafting system will select. My only idea is to allow the player to 'dissable' certain aspects from being placed in the output list. For example if your encoding coal, if you disable potentia then only ignis will show up in the craftable list. Even though it will in-fact produce potentia essentia when distilled.

**Comment by Nividica** [comment]
Making some headway now!
![essentiaautocrafting](https://cloud.githubusercontent.com/assets/1585989/12049390/84413d08-aeb4-11e5-8c12-7f793419a043.png)

**Comment by Nividica** [comment]
Well damn. The system really did not like having two outputs. Looks like this solves my previous issue, but each recipe can only produce one output :-/

**Comment by Nividica** [comment]
Essentia autocrafting is functional, all that is left is to test, test, test, and then add lore + recipe.
![distillationencoder_gui](https://cloud.githubusercontent.com/assets/1585989/12056867/a6f37398-af09-11e5-8456-08c6a8520693.png)
![essentiaautocraftingsetup](https://cloud.githubusercontent.com/assets/1585989/12056868/a6f38e3c-af09-11e5-836a-27114d9343f1.png)

**Comment by Dream-Master** [comment]
looks nice

**Comment by lehjr** [comment]
Looks like someone has been busy. Fantastic job!

**Comment by Nividica** [comment]
Totally lied about having to just add the lore and recipe, forgot about making the terminal support craftable essentia -.-
This should all be done in a few days.

**Comment by Nividica** [comment]
Ok, ~now~ all thats left is the lore, recipe, and a texure.
