### ISSUE TITLE
DigiVis Buffer/Capacitor

### ISSUE THREAD

**Issue by Nividica** [Nividica/ThaumicEnergistics#68]
Provide a way to buffer imported centivis. And allow the A.C.T., and any future AE devices, to use the buffered vis.

Setup:
node->VRI->ACT(s) => node->VRI->Buffer->ACT(s)

Restrictions:
A buffer can only have a single centivis input.
An A.C.T. can only have a single centivis input.
Buffered centivis can not be exported back into a relay system.

**Comment by Anarcraft** [comment]
What about having a primary VRI (accepting CV) able to link to other VRIs (to output CV)?
