### ISSUE TITLE
well, i have a new report for you

### ISSUE THREAD

**Issue by Sailren** [Nividica/ThaumicEnergistics#89]
happens at start

http://paste.ubuntu.com/9076917/

is your mod not compatible with RV2?

**Comment by Dajudge06** [comment]
What is causing this error? I just updated to your current version and it tripped this same crash report. I updated after crashing this morning when I opened my essentia terminal.

**Comment by Nividica** [comment]
This error was caused from using mismatched versions of AE2 and ThE. The most recent version of ThE requires AE2-RV2-Beta7. If you have RV1 you will have to use the RV1 build of ThE as provided on the MCF page.
