### ISSUE TITLE
Power Generation

### ISSUE THREAD

**Issue by Nividica** [Nividica/ThaumicEnergistics#92]
Implemented: Essentia Vibration Chamber
Planned: Arcane Reactor

**Comment by zlyfire** [comment]
Idea for power generation: Use Centi-Vis to power the network somehow?

**Comment by Nividica** [comment]
That will be a part of the final power producing construct.

**Comment by Nividica** [comment]
Essentia Vibration Chamber added in build 0.8.10.8

**Comment by Nividica** [comment]
I have decided not to implement the reactor at this time.
